ATU100_PIC16F1938: include/main.h File Reference
main.h File Reference
ATU-100 EXT firmware definitions for PIC16F1938 main program.
#include <xc.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include "extratypes.h"
#include "preprocessor.h"
#include "common.h"
#include "eeprom_map.h"
#include "pic_init.h"
Definitions and Macros
#define SWR_NO_TUNE_UNDER (110) /* SWR: 1.1 */
The SWR value under which an attempt to tune is not made.
#define SWR_TUNE_TARGET (120) /* SWR: 1.2 */
The target SWR that tuning attempts to acheive.
Function Declarations
void btn_push (void)
void lcd_prep (void)
void lcd_swr (int)
void lcd_pwr (void)
void show_pwr (int, int)
void lcd_ind (void)
void crypto (void)
void show_reset (void)
void init_runtime_data_from_eeprom (void)
Initialize the runtime data used by the ATU-100 firmware from the data stored in the EEPROM.
void test_init (void)
void button_proc (void)
Handle the process of the buttons being pressed.
void button_proc_test (void)
Handle the process of the buttons being pressed (in test mode)
void button_delay (void)
void show_loss (void)
void atu_reset (void)
int get_reverse (void)
int get_forward (void)
int correction (int)
void get_swr (void)
void get_pwr (void)
void set_sw (char SW)
Set the state of the switch.
void coarse_cap ()
void sharp_cap ()
void sharp_ind ()
void coarse_tune ()
void tune (void)
void sub_tune (void)
void set_ind (uint8_t Ind)
void set_cap (uint8_t Cap)
Variable Declarations
static char SW = 0
static char step_cap = 0
static char step_ind = 0
static char L_linear = 0
static char C_linear = 0
static char L_q = 7
static char C_q = 7
static char D_correction = 1
static char L_invert = 0
static char L_mult = 1
static char C_mult = 1
static char P_High = 0
static char K_Mult = 32
static char Overload = 0
static char Loss_ind = 0
static char Relay_off = 0
int relay_delay_ms
static int min_for_start
static int max_for_start
static int max_swr
int PWR
int P_max
int swr_a
char rready = 0
char p_cnt = 0
int SWR
Holds the current SWR.
bit_byte_t ind
bit_byte_t cap
Detailed File Description
ATU-100 EXT firmware definitions for PIC16F1938 main program.
Version
3.2.1
Author
Gerad Munsch gmuns.nosp@m.ch@k.nosp@m.d9qzo.nosp@m..com
Date
December 2021
Author
David Fainitski
Date
2016
Definition in file main.h.
Definitions and Macros
SWR_NO_TUNE_UNDER
#define SWR_NO_TUNE_UNDER (110) /* SWR: 1.1 */
The SWR value under which an attempt to tune is not made.
Note
The default value is 110 (for an SWR value of 1.10).
Definition at line 41 of file main.h.
SWR_TUNE_TARGET
#define SWR_TUNE_TARGET (120) /* SWR: 1.2 */
The target SWR that tuning attempts to acheive.
Note
The default value is 120 (for an SWR value of 1.20).
Definition at line 50 of file main.h.
Function Definitions
atu_reset()
void atu_reset (void)
Definition at line 438 of file main.h.
                 {
    ind.byte = 0;
    cap.byte = 0;
    set_ind(ind.byte);
    set_cap(cap.byte);
    Delay_ms(relay_delay_ms);
}
References bit_byte_t::byte, cap, ind, relay_delay_ms, set_cap(), and set_ind().
Referenced by show_reset(), sub_tune(), test_init(), and tune().
btn_push()
void btn_push (void)
Definition at line 654 of file main.c.
                {
    CLEAR_WDT();
    if ((type == 4) || (type == 5)) {                               // 128*64 OLED
        led_wr_str(2, 16 + 12 * 4, "TUNE", 4);
    } else if (type != 0) {                                         // 1602 LCD & 128*32 OLED
        led_wr_str(1, 4, "TUNE", 4);
    } else {
        LATBbits.LATB6 = 1;
        LATBbits.LATB7 = 1;
    }
    tune();
    if (type == 0) {                                                /* Use a 2-color (green/red) common-anode LED */
        if (SWR <= 150) {                                           /* SWR <= 1.50: GREEN */
            LATBbits.LATB6 = 0;
            LATBbits.LATB7 = 1;
        } else if (SWR <= 250) {                                    /* 1.50 < SWR <= 2.50: ORANGE */
            PORTBbits.RB6 = 0;
            PORTBbits.RB7 = 0;
        } else {                                                    /* SWR > 2.50: RED */
            PORTBbits.RB6 = 1;
            PORTBbits.RB7 = 0;
        }
    } else if ((Loss_mode == 0) || (Loss_ind == 0)) {
        lcd_ind();
    }
    EEPROM_Write(255, cap.byte);
    EEPROM_Write(254, ind.byte);
    EEPROM_Write(253, SW);
    EEPROM_Write(252, swr_a / 256);
    EEPROM_Write(251, swr_a % 256);
    SWR_old = 10000;
    Power_old = 10000;
    lcd_pwr();
    SWR_fixed_old = SWR;
    p_Tx = 0;
    n_Tx = 1;
    CLEAR_WDT();
    return;
}
References bit_byte_t::byte, cap, CLEAR_WDT, ind, lcd_ind(), lcd_pwr(), led_wr_str(), Loss_ind, Loss_mode, n_Tx, p_Tx, Power_old, SW, SWR, swr_a, SWR_fixed_old, SWR_old, tune(), and type.
Referenced by button_proc().
button_delay()
void button_delay (void)
Definition at line 813 of file main.c.
                    {
    if ((Button(&PORTB, 0, 25, 0)) || (Button(&PORTB, 1, 25, 0)) || (Button(&PORTB, 2, 25, 0))) {
        but = 1;
    }
    return;
}
References but.
Referenced by lcd_pwr().
button_proc()
void button_proc (void)
Handle the process of the buttons being pressed.
This function handles the process of the buttons being pressed; it tests whether it was a momentary press, or a long press, and acts accordingly.
The buttons that are handled are:
TUNE
BYPASS
AUTO
Definition at line 452 of file main.c.
                       {
    if ((tune_btn_release == 0) && Button(&PORTB, 0, 50, 1)) {
        tune_btn_release = 1;
    }
    if ((tune_btn_release == 0) && Button(&PORTB, 0, 50, 0)) {
        dysp_cnt = Dysp_delay * dysp_cnt_mult;
    }
    if ((Button(&PORTB, 0, 50, 0) && tune_btn_release) || Soft_tune) {
        if (dysp == 0) { // display ON
            if (Relay_off == 1) {
                set_ind(ind.byte);
                set_cap(cap.byte);
                set_sw(SW);
            }
            dysp = 1;
            display_on();
            dysp_cnt = Dysp_delay * dysp_cnt_mult;
            return;
        }
        dysp_cnt = Dysp_delay * dysp_cnt_mult;
        Delay_ms(250);
        CLEAR_WDT();
        if ((Soft_tune == 0) && (PORTBbits.RB0 == 1)) {                 // short press button
            show_reset();
            bypas = 0;
        } else {                                                        // long press button
            p_Tx = 1;                                                   // Set the active-high TX request output
            n_Tx = 0;                                                   // Set the active-low TX request output
            Delay_ms(250);
            btn_push();
            bypas = 0;
            Soft_tune = 0;
            tune_btn_release = 0;
        }
    }
    if (Button(&PORTB, 2, 50, 0)) {                                     // BYP button
        if (dysp == 0) {                                                // display ON
            if (Relay_off == 1) {
                set_ind(ind.byte);
                set_cap(cap.byte);
                set_sw(SW);
            }
            dysp = 1;
            display_on();
            dysp_cnt = (int)(Dysp_delay * dysp_cnt_mult);
            return;
        }
        dysp_cnt = (int)(Dysp_delay * dysp_cnt_mult);
        CLEAR_WDT();
        if (bypas == 0) {
            bypas = 1;
            cap_mem = cap.byte;
            ind_mem = ind.byte;
            SW_mem = SW;
            cap.byte = 0;
            if (L_invert) {
                ind.byte = 255;
            } else {
                ind.byte = 0;
            }
            SW = 1;
            set_ind(ind.byte);
            set_cap(cap.byte);
            set_sw(SW);
            if (Loss_mode == 0) {
                lcd_ind();
            }
            Auto_mem = Auto;
            Auto = 0;
        } else {
            bypas = 0;
            cap.byte = cap_mem;
            ind.byte = ind_mem;
            SW = SW_mem;
            set_cap(cap.byte);
            set_ind(ind.byte);
            set_sw(SW);
            if (Loss_mode == 0) {
                lcd_ind();
            }
            Auto = Auto_mem;
        }
        if ((type == 4) || (type == 5)) {                               // 128*64 OLED
            if (Auto && !bypas) {
                led_wr_str(0, 16 + 8 * 12, ".", 1);
            } else if (!Auto && bypas) {
                led_wr_str(0, 16 + 8 * 12, "_", 1);
            } else {
                led_wr_str(0, 16 + 8 * 12, " ", 1);
            }
        } else if (type != 0) {                                         // 1602 LCD or 128*32 OLED
            if (Auto && !bypas) {
                led_wr_str(0, 8, ".", 1);
            } else if (!Auto && bypas) {
                led_wr_str(0, 8, "_", 1);
            } else {
                led_wr_str(0, 8, " ", 1);
            }
        }
        CLEAR_WDT();
        while (Button(&PORTB, 2, 50, 0)) {
            lcd_pwr();
            CLEAR_WDT();
        }
    }
    if (Button(&PORTB, 1, 50, 0) && (bypas == 0)) {                     // "AUTO" button
        if (dysp == 0) {                                                // display ON
            if (Relay_off == 1) {
                set_ind(ind.byte);
                set_cap(cap.byte);
                set_sw(SW);
            }
            dysp = 1;
            display_on();
            dysp_cnt = (int)(Dysp_delay * dysp_cnt_mult);
            return;
        }
        dysp_cnt = (int)(Dysp_delay * dysp_cnt_mult);
        CLEAR_WDT();
        if (Auto == 0) {
            Auto = 1;
        } else {
            Auto = 0;
        }
        EEPROM_Write(EEPROM_AUTO_MODE, Auto);
        if ((type == 4) || (type == 5)) {                               // 128*64 OLED
            if (Auto & !bypas) led_wr_str(0, 16 + 8 * 12, ".", 1);
            else if (!Auto && bypas) led_wr_str(0, 16 + 8 * 12, "_", 1);
            else led_wr_str(0, 16 + 8 * 12, " ", 1);
        } else if (type != 0) {                                         // 1602 LCD or 128*32 OLED
            if (Auto && !bypas) led_wr_str(0, 8, ".", 1);
            else if (!Auto && bypas) led_wr_str(0, 8, "_", 1);
            else led_wr_str(0, 8, " ", 1);
        }
        CLEAR_WDT();
        while (Button(&PORTB, 1, 50, 0)) {
            lcd_pwr();
            CLEAR_WDT();
        }
    }
    return;
}
References Auto, Auto_mem, btn_push(), bypas, bit_byte_t::byte, cap, cap_mem, CLEAR_WDT, display_on(), dysp, dysp_cnt, dysp_cnt_mult, Dysp_delay, EEPROM_AUTO_MODE, ind, ind_mem, L_invert, lcd_ind(), lcd_pwr(), led_wr_str(), Loss_mode, n_Tx, p_Tx, Relay_off, set_cap(), set_ind(), set_sw(), show_reset(), Soft_tune, SW, SW_mem, tune_btn_release, and type.
Referenced by main().
button_proc_test()
void button_proc_test (void)
Handle the process of the buttons being pressed (in test mode)
This function handles the process of the buttons being pressed; it tests whether it was a momentary press, or a long press, and acts accordingly.
The buttons that are handled are:
TUNE
BYPASS
AUTO
Note
This function is called only in "test" mode.
Definition at line 367 of file main.c.
{
    /* Check to see if the "TUNE" button is pressed... */
    if (Button(&PORTB, 0, 50, 0)) {                                 // "TUNE" button
        Delay_ms(250);
        CLEAR_WDT();
        if (PORTBbits.RB0 == 1) {                                   // short press button
            if (SW == 0) {
                SW = 1;
            } else {
                SW = 0;
            }
            set_sw(SW);
            lcd_ind();
        } else {                                                    // long press button
            if (L == 1) {
                L = 0;
            } else {
                L = 1;
            }
            if (L == 1) {
                if ((type == 4) || (type == 5)) {                   // 128*64 OLED
                    led_wr_str(0, 16 + 12 * 8, "l", 1);
                } else if (type != 0) {                             // 1602 LCD & 128*32 OLED
                    led_wr_str(0, 8, "l", 1);
                }
            } else {
                if ((type == 4) || (type == 5)) {                   // 128*64 OLED
                    led_wr_str(0, 16 + 12 * 8, "c", 1);
                } else if (type != 0) {                             // 1602 LCD & 128*32 OLED
                    led_wr_str(0, 8, "c", 1);
                }
            }
        }
        while (Button(&PORTB, 0, 50, 0)) {
            lcd_pwr();
            CLEAR_WDT();
        }
    } // END Tune btn
    /* Check to see if the "BYP" (bypass) button is pressed... */
    if (Button(&PORTB, 2, 50, 0)) {
        CLEAR_WDT();
        while (PORTBbits.RB2 == 0) {
            if (L && (ind.byte < 32 * L_mult - 1)) {
                ind.byte++;
                set_ind(ind.byte);
            } else if (!L && (cap.byte < 32 * L_mult - 1)) {
                cap.byte++;
                set_cap(cap.byte);
            }
            lcd_ind();
            lcd_pwr();
            Delay_ms(30);
            CLEAR_WDT();
        }
    } // end of BYP button
    /* Check to see if the "AUTO" button is pressed... */
    if (Button(&PORTB, 1, 50, 0) && (bypas == 0)) {
        CLEAR_WDT();
        while (PORTBbits.RB1 == 0) {
            if (L && (ind.byte > 0)) {
                ind.byte--;
                set_ind(ind.byte);
            } else if (!L && (cap.byte > 0)) {
                cap.byte--;
                set_cap(cap.byte);
            }
            lcd_ind();
            lcd_pwr();
            Delay_ms(30);
            CLEAR_WDT();
        }
    }
    return;
}
References bypas, bit_byte_t::byte, cap, CLEAR_WDT, ind, L, L_mult, lcd_ind(), lcd_pwr(), led_wr_str(), set_cap(), set_ind(), set_sw(), SW, and type.
Referenced by main().
coarse_cap()
void coarse_cap ()
Definition at line 446 of file main.h.
                  {
    char step = 3;
    char count;
    int min_swr;
    cap.byte = 0;
    set_cap(cap.byte);
    step_cap = step;
    get_swr();
    if (SWR == 0) {
        return;
    }
    min_swr = SWR + SWR / 20;
    for (count = step; count <= 31;) {
        set_cap(count * C_mult);
        get_swr();
        if (SWR == 0) {
            return;
        }
        if (SWR < min_swr) {
            min_swr = SWR + SWR / 20;
            cap.byte = count * C_mult;
            step_cap = step;
            if (SWR < 120) {
                break;
            }
            count += step;
            if ((C_linear == 0) && (count == 9)) {
                count = 8;
            } else if ((C_linear == 0) && (count == 17)) {
                count = 16;
                step = 4;
            }
        } else {
            break;
        }
    }
    set_cap(cap.byte);
    return;
}
References bit_byte_t::byte, C_linear, C_mult, cap, get_swr(), set_cap(), step_cap, and SWR.
Referenced by coarse_tune().
coarse_tune()
void coarse_tune ()
Definition at line 492 of file main.h.
                   {
    char step = 3;
    char count;
    char mem_cap;
    char mem_step_cap;
    int min_swr;
    mem_cap = 0;
    step_ind = step;
    mem_step_cap = 3;
    min_swr = SWR + SWR / 20;
    for (count = 0; count <= 31;) {
        set_ind(count * L_mult);
        coarse_cap();
        get_swr();
        if (SWR == 0) {
            return;
        }
        if (SWR < min_swr) {
            min_swr = SWR + SWR / 20;
            ind.byte = count * L_mult;
            mem_cap = cap.byte;
            step_ind = step;
            mem_step_cap = step_cap;
            if (SWR < 120) {
                break;
            }
            count += step;
            if ((L_linear == 0) && (count == 9)) {
                count = 8;
            } else if ((L_linear == 0) && (count == 17)) {
                count = 16;
                step = 4;
            }
        } else {
            break;
        }
    }
    cap.byte = mem_cap;
    set_ind(ind.byte);
    set_cap(cap.byte);
    step_cap = mem_step_cap;
    Delay_ms(10);
    return;
}
References bit_byte_t::byte, cap, coarse_cap(), get_swr(), ind, L_linear, L_mult, set_cap(), set_ind(), step_cap, step_ind, and SWR.
Referenced by sub_tune().
correction()
int correction (int input)
Definition at line 154 of file main.h.
{
    if (input <= 80) {
        return 0;
    }
    if (input <= 171) {
        input += 244;
    } else if (input <= 328) {
        input += 254;
    } else if (input <= 582) {
        input += 280;
    } else if (input <= 820) {
        input += 297;
    } else if (input <= 1100) {
        input += 310;
    } else if (input <= 2181) {
        input += 430;
    } else if (input <= 3322) {
        input += 484;
    } else if (input <= 4623) {
        input += 530;
    } else if (input <= 5862) {
        input += 648;
    } else if (input <= 7146) {
        input += 743;
    } else if (input <= 8502) {
        input += 800;
    } else if (input <= 10500) {
        input += 840;
    } else {
        input += 860;
    }
    return input;
}
Referenced by get_pwr().
crypto()
void crypto (void)
get_forward()
int get_forward (void)
Definition at line 234 of file main.h.
                  {
    int adc_result_forward_pwr;
#if 0
    FVRCON = 0b10000001; // ADC 1024 vmV Vref
    while (FVRCONbits.FVRRDY == 0);
    adc_result_forward_pwr = ADC_Get_Sample(1);
    if (adc_result_forward_pwr <= 1000) {
        Overload = 0;
        return (adc_result_forward_pwr);
    }
    FVRCON = 0b10000010; // ADC 2048 vmV Vref
    while (FVRCONbits.FVRRDY == 0);
    adc_result_forward_pwr = ADC_Get_Sample(1);
    if (adc_result_forward_pwr <= 1000) {
        Overload = 0;
        return (adc_result_forward_pwr * 2);
    }
    FVRCON = 0b10000011; // ADC 4096 vmV Vref
    while (FVRCONbits.FVRRDY == 0);
    adc_result_forward_pwr = ADC_Get_Sample(1);
    if (adc_result_forward_pwr > 1000) {
        Overload = 1;
    } else {
        Overload = 0;
    }
    return (adc_result_forward_pwr * 4);
#else
    uint8_t iteration = 0;
    do {
        FVRCON = ((iteration + 1) | 0b10000000);    /* Set ADC Vref to (1024 * 2^iteration) mV */
        while (FVRCONbits.FVRRDY == 0);             /* Wait for FVRCON to provide a stable Vref to the ADC... */
        /* Get reverse power reading from the ADC */
        adc_result_forward_pwr = ADC_Get_Sample(1);
    } while ((adc_result_forward_pwr <= 1000) || (iteration < 3));
    if (adc_result_forward_pwr > 1000) {
        Overload = 1;
    } else {
        Overload = 0;
    }
    return (adc_result_forward_pwr * (1 << iteration));
#endif
}
References Overload.
Referenced by get_pwr().
get_pwr()
void get_pwr (void)
Definition at line 289 of file main.h.
               {
    long pwr_fwd;
    long pwr_rev;
    float pwr_calc;
    CLEAR_WDT();
    pwr_fwd = get_forward();            /* Get forward power */
    pwr_rev = get_reverse();            /* Get reverse power */
    /* Perform power correction/scaling */
    if (D_correction == 1) {
        pwr_calc = (float)correction(pwr_fwd * 3);
    } else {
        pwr_calc = (float)(pwr_fwd * 3);
    }
    /* Check if the reverse power exceeds the forward power */
    if (pwr_rev >= pwr_fwd) {
        /* If the reverse power exceeds the forward power, max out the forward SWR measurement... */
        pwr_fwd = 999;
    } else {
        /* Calculate the forward power ratio */
        pwr_fwd = ((pwr_fwd + pwr_rev) * 100) / (pwr_fwd - pwr_rev);
        /* If the calculated forward power ratio exceeds 999, max it out at 999 */
        if (pwr_fwd > 999) {
            pwr_fwd = 999;
        }
    }
    pwr_calc = pwr_calc * K_Mult / 1000.0;              // mV to Volts on Input
    pwr_calc = pwr_calc / 1.414;
    /* Check to see if the tuner is in "high power" mode */
    if (P_High == 1) {
        pwr_calc = pwr_calc * pwr_calc / 50.0;          // 0 - 1500 (1,500 Watts)
    } else {
        pwr_calc = pwr_calc * pwr_calc / 5.0;           // 0 - 1510 (151.0 Watts)
    }
    pwr_calc = pwr_calc + 0.5;                          // rounding
    PWR = pwr_calc;
    if (pwr_fwd < 100) {
        SWR = 999;
    } else {
        SWR = pwr_fwd;
    }
    return;
}
References CLEAR_WDT, correction(), D_correction, get_forward(), get_reverse(), K_Mult, P_High, PWR, and SWR.
Referenced by get_swr(), and lcd_pwr().
get_reverse()
int get_reverse (void)
Definition at line 192 of file main.h.
                  {
    int adc_result_reverse_pwr;
#if 0
    FVRCON = 0b10000001; // ADC 1024 vmV Vref
    while (FVRCONbits.FVRRDY == 0);
    adc_result_reverse_pwr = ADC_Get_Sample(0);
    if (adc_result_reverse_pwr <= 1000) {
        return (adc_result_reverse_pwr);
    }
    FVRCON = 0b10000010; // ADC 2048 vmV Vref
    while (FVRCONbits.FVRRDY == 0);
    adc_result_reverse_pwr = ADC_Get_Sample(0);
    if (adc_result_reverse_pwr <= 1000) {
        return (adc_result_reverse_pwr * 2);
    }
    FVRCON = 0b10000011; // ADC 4096 vmV Vref
    while (FVRCONbits.FVRRDY == 0);
    adc_result_reverse_pwr = ADC_Get_Sample(0);
    return (adc_result_reverse_pwr * 4);
#else
    uint8_t iteration = 0;
    do {
        FVRCON = ((iteration + 1) | 0b10000000);    /* Set ADC Vref to (1024 * 2^iteration) mV */
        while (FVRCONbits.FVRRDY == 0);             /* Wait for FVRCON to provide a stable Vref to the ADC... */
        /* Get reverse power reading from the ADC */
        adc_result_reverse_pwr = ADC_Get_Sample(0);
    } while ((adc_result_reverse_pwr <= 1000) || (iteration < 3));
    return (adc_result_reverse_pwr * (1 << iteration));
#endif
}
Referenced by get_pwr().
get_swr()
void get_swr (void)
Definition at line 340 of file main.h.
               {
    get_pwr();
    if (p_cnt != 100) {
        p_cnt += 1;
        if (PWR > P_max) {
            P_max = PWR;
        }
    } else {
        p_cnt = 0;
        show_pwr(P_max, SWR);
        P_max = 0;
    }
    while ((PWR < min_for_start) || ((PWR > max_for_start) && (max_for_start > 0))) {   // waiting for good power
        CLEAR_WDT();
        get_pwr();
        if (p_cnt != 100) {
            p_cnt += 1;
            if (PWR > P_max) {
                P_max = PWR;
            }
        } else {
            p_cnt = 0;
            show_pwr(P_max, SWR);
            P_max = 0;
        }
        if (Button(&PORTB, 0, 5, 1)) {
            rready = 1;
        }
        if ((rready == 1) && Button(&PORTB, 0, 5, 0)) { //  press button  Tune
            show_reset();
            SWR = 0;
            return;
        }
    } //  good power
    return;
}
References CLEAR_WDT, get_pwr(), max_for_start, min_for_start, p_cnt, P_max, PWR, rready, show_pwr(), show_reset(), and SWR.
Referenced by coarse_cap(), coarse_tune(), sharp_cap(), sharp_ind(), sub_tune(), and tune().
init_runtime_data_from_eeprom()
void init_runtime_data_from_eeprom (void)
Initialize the runtime data used by the ATU-100 firmware from the data stored in the EEPROM.
Definition at line 1297 of file main.c.
{
    CLEAR_WDT();
#if defined(READ_OLED_ADDR_FROM_EEPROM)
    oled_addr = EEPROM_Read(EEPROM_OLED_ADDR);                                                  /* OLED I2C address */
#endif
    type = EEPROM_Read(EEPROM_DISP_TYPE);                                                       /* type of display */
    if (EEPROM_Read(EEPROM_AUTO_MODE) == 1) {                                                   /* Check if AUTO mode should be enabled */
        Auto = 1;
    }
    relay_delay_ms = Bcd2Dec(EEPROM_Read(EEPROM_RELAY_DELAY));                                  /* Relay's Delay */
    Auto_delta = Bcd2Dec(EEPROM_Read(EEPROM_AUTO_DELTA)) * 10;                                  /* Auto_delta */
    min_for_start = Bcd2Dec(EEPROM_Read(EEPROM_PMIN_FOR_START)) * 10;                           /* Min power for starting tuning */
    max_for_start = Bcd2Dec(EEPROM_Read(EEPROM_PMAX_FOR_START)) * 10;                           /* Max power for starting tuning */
    // 7  - shift down
    // 8 - shift left
    max_swr = Bcd2Dec(EEPROM_Read(EEPROM_MAX_SWR)) * 10;                                        /* Max SWR */
    L_q = EEPROM_Read(EEPROM_L_Q);
    L_linear = EEPROM_Read(EEPROM_L_LINEAR);
    C_q = EEPROM_Read(EEPROM_C_Q);
    C_linear = EEPROM_Read(EEPROM_C_LINEAR);
    D_correction = EEPROM_Read(EEPROM_D_CORRECTION);
    L_invert = EEPROM_Read(EEPROM_L_INVERT);
    CLEAR_WDT();
    inds.L1 = Bcd2Dec(EEPROM_Read(EEPROM_L1_HI)) * 100 + Bcd2Dec(EEPROM_Read(EEPROM_L1_LO));    /* Ind1 */
    inds.L2 = Bcd2Dec(EEPROM_Read(EEPROM_L2_HI)) * 100 + Bcd2Dec(EEPROM_Read(EEPROM_L2_LO));    /* Ind2 */
    inds.L3 = Bcd2Dec(EEPROM_Read(EEPROM_L3_HI)) * 100 + Bcd2Dec(EEPROM_Read(EEPROM_L3_LO));    /* Ind3 */
    inds.L4 = Bcd2Dec(EEPROM_Read(EEPROM_L4_HI)) * 100 + Bcd2Dec(EEPROM_Read(EEPROM_L4_LO));    /* Ind4 */
    inds.L5 = Bcd2Dec(EEPROM_Read(EEPROM_L5_HI)) * 100 + Bcd2Dec(EEPROM_Read(EEPROM_L5_LO));    /* Ind5 */
    inds.L6 = Bcd2Dec(EEPROM_Read(EEPROM_L6_HI)) * 100 + Bcd2Dec(EEPROM_Read(EEPROM_L6_LO));    /* Ind6 */
    inds.L7 = Bcd2Dec(EEPROM_Read(EEPROM_L7_HI)) * 100 + Bcd2Dec(EEPROM_Read(EEPROM_L7_LO));    /* Ind7 */
    caps.C1 = Bcd2Dec(EEPROM_Read(EEPROM_C1_HI)) * 100 + Bcd2Dec(EEPROM_Read(EEPROM_C1_LO));    /* Cap1 */
    caps.C2 = Bcd2Dec(EEPROM_Read(EEPROM_C2_HI)) * 100 + Bcd2Dec(EEPROM_Read(EEPROM_C2_LO));    /* Cap2 */
    caps.C3 = Bcd2Dec(EEPROM_Read(EEPROM_C3_HI)) * 100 + Bcd2Dec(EEPROM_Read(EEPROM_C3_LO));    /* Cap3 */
    caps.C4 = Bcd2Dec(EEPROM_Read(EEPROM_C4_HI)) * 100 + Bcd2Dec(EEPROM_Read(EEPROM_C4_LO));    /* Cap4 */
    caps.C5 = Bcd2Dec(EEPROM_Read(EEPROM_C5_HI)) * 100 + Bcd2Dec(EEPROM_Read(EEPROM_C5_LO));    /* Cap5 */
    caps.C6 = Bcd2Dec(EEPROM_Read(EEPROM_C6_HI)) * 100 + Bcd2Dec(EEPROM_Read(EEPROM_C6_LO));    /* Cap6 */
    caps.C7 = Bcd2Dec(EEPROM_Read(EEPROM_C7_HI)) * 100 + Bcd2Dec(EEPROM_Read(EEPROM_C7_LO));    /* Cap7 */
    P_High = EEPROM_Read(EEPROM_HIGH_PWR_MODE);                                                 /* High power mode */
    K_Mult = Bcd2Dec(EEPROM_Read(EEPROM_TANDEM_MATCH_RATIO));                                   /* Tandem Match ratio */
    Dysp_delay = Bcd2Dec(EEPROM_Read(EEPROM_DISPLAY_ON_DELAY));                                 /* Display ON delay */
    Loss_ind = EEPROM_Read(0x33);
    Fid_loss = Bcd2Dec(EEPROM_Read(0x34));
    Relay_off = Bcd2Dec(EEPROM_Read(0x35));
    CLEAR_WDT();
    return;
}
References Auto, Auto_delta, capacitor_values_t::C1, capacitor_values_t::C2, capacitor_values_t::C3, capacitor_values_t::C4, capacitor_values_t::C5, capacitor_values_t::C6, capacitor_values_t::C7, C_linear, C_q, caps, CLEAR_WDT, D_correction, Dysp_delay, EEPROM_AUTO_DELTA, EEPROM_AUTO_MODE, EEPROM_C1_HI, EEPROM_C1_LO, EEPROM_C2_HI, EEPROM_C2_LO, EEPROM_C3_HI, EEPROM_C3_LO, EEPROM_C4_HI, EEPROM_C4_LO, EEPROM_C5_HI, EEPROM_C5_LO, EEPROM_C6_HI, EEPROM_C6_LO, EEPROM_C7_HI, EEPROM_C7_LO, EEPROM_C_LINEAR, EEPROM_C_Q, EEPROM_D_CORRECTION, EEPROM_DISP_TYPE, EEPROM_DISPLAY_ON_DELAY, EEPROM_HIGH_PWR_MODE, EEPROM_L1_HI, EEPROM_L1_LO, EEPROM_L2_HI, EEPROM_L2_LO, EEPROM_L3_HI, EEPROM_L3_LO, EEPROM_L4_HI, EEPROM_L4_LO, EEPROM_L5_HI, EEPROM_L5_LO, EEPROM_L6_HI, EEPROM_L6_LO, EEPROM_L7_HI, EEPROM_L7_LO, EEPROM_L_INVERT, EEPROM_L_LINEAR, EEPROM_L_Q, EEPROM_MAX_SWR, EEPROM_OLED_ADDR, EEPROM_PMAX_FOR_START, EEPROM_PMIN_FOR_START, EEPROM_RELAY_DELAY, EEPROM_TANDEM_MATCH_RATIO, Fid_loss, inds, K_Mult, inductor_values_t::L1, inductor_values_t::L2, inductor_values_t::L3, inductor_values_t::L4, inductor_values_t::L5, inductor_values_t::L6, inductor_values_t::L7, L_invert, L_linear, L_q, Loss_ind, max_for_start, max_swr, min_for_start, P_High, relay_delay_ms, Relay_off, and type.
Referenced by main().
lcd_ind()
void lcd_ind (void)
Definition at line 1121 of file main.c.
               {
    char column;
    CLEAR_WDT();
    if (1) {
        work_int = 0;
        if (ind.B0) work_int += inds.L1;
        if (ind.B1) work_int += inds.L2;
        if (ind.B2) work_int += inds.L3;
        if (ind.B3) work_int += inds.L4;
        if (ind.B4) work_int += inds.L5;
        if (ind.B5) work_int += inds.L6;
        if (ind.B6) work_int += inds.L7;
        if (work_int > 9999) { // more then 9999 nH
            work_int += 50; // round
            IntToStr(work_int, work_str);
            work_str_2[0] = work_str[1];
            work_str_2[1] = work_str[2];
            work_str_2[2] = '.';
            work_str_2[3] = work_str[3];
        } else {
            IntToStr(work_int, work_str);
            if (work_str[2] != ' ') work_str_2[0] = work_str[2];
            else work_str_2[0] = '0';
            work_str_2[1] = '.';
            if (work_str[3] != ' ') work_str_2[2] = work_str[3];
            else work_str_2[2] = '0';
            if (work_str[4] != ' ') work_str_2[3] = work_str[4];
            else work_str_2[3] = '0';
        }
#if 0
        if (type == 4 || type == 5) { // 128*64 OLED
            if (SW == 1) column = 4;
            else column = 6;
            led_wr_str(column, 16, "L=", 2);
            led_wr_str(column, 16 + 6 * 12, "uH", 2);
            led_wr_str(column, 16 + 2 * 12, work_str_2, 4);
        } else if (type == 2 || type == 3) {// 128*32 OLED
            if (SW == 1) column = 0;
            else column = 1;
            led_wr_str(column, 9, "L=", 2);
            led_wr_str(column, 15, "uH", 2);
            led_wr_str(column, 11, work_str_2, 4);
        } else if (type == 1) { //  1602 LCD
            if (SW == 1) column = 0;
            else column = 1;
            led_wr_str(column, 9, "L=", 2);
            led_wr_str(column, 15, "u", 1);
            led_wr_str(column, 11, work_str_2, 4);
        }
#else
        switch (type) {
            case 4:
            case 5:
                column = SW ? 4 : 6;
                led_wr_str(column, 16, "L=", 2);
                led_wr_str(column, 16 + 6 * 12, "uH", 2);
                led_wr_str(column, 16 + 2 * 12, work_str_2, 4);
                break;
            case 2:
            case 3:
                column = SW ? 0 : 1;
                led_wr_str(column, 9, "L=", 2);
                led_wr_str(column, 15, "uH", 2);
                led_wr_str(column, 11, work_str_2, 4);
                break;
            case 1:
                column = SW ? 0 : 1;
                led_wr_str(column, 9, "L=", 2);
                led_wr_str(column, 15, "u", 1);
                led_wr_str(column, 11, work_str_2, 4);
                break;
            default:
                break;
        }
#endif
    }
    CLEAR_WDT();
    if (1) {
        work_int = 0;
        if (cap.B0) work_int += caps.C1;
        if (cap.B1) work_int += caps.C2;
        if (cap.B2) work_int += caps.C3;
        if (cap.B3) work_int += caps.C4;
        if (cap.B4) work_int += caps.C5;
        if (cap.B5) work_int += caps.C6;
        if (cap.B6) work_int += caps.C7;
        IntToStr(work_int, work_str);
        work_str_2[0] = work_str[2];
        work_str_2[1] = work_str[3];
        work_str_2[2] = work_str[4];
        work_str_2[3] = work_str[5];
        if (type == 4 || type == 5) { // 128*64 OLED
            if (SW == 1) column = 6;
            else column = 4;
            led_wr_str(column, 16, "C=", 2);
            led_wr_str(column, 16 + 6 * 12, "pF", 2);
            led_wr_str(column, 16 + 2 * 12, work_str_2, 4);
        } else if (type == 2 || type == 3) {// 128*32 OLED
            if (SW == 1) column = 1;
            else column = 0;
            led_wr_str(column, 9, "C=", 2);
            led_wr_str(column, 15, "pF", 2);
            led_wr_str(column, 11, work_str_2, 4);
        } else if (type == 1) { // 1602 LCD
            if (SW == 1) column = 1;
            else column = 0;
            led_wr_str(column, 9, "C=", 2);
            led_wr_str(column, 15, "p", 1);
            led_wr_str(column, 11, work_str_2, 4);
        }
    }
    CLEAR_WDT();
    return;
}
References capacitor_values_t::C1, capacitor_values_t::C2, capacitor_values_t::C3, capacitor_values_t::C4, capacitor_values_t::C5, capacitor_values_t::C6, capacitor_values_t::C7, cap, caps, CLEAR_WDT, ind, inds, inductor_values_t::L1, inductor_values_t::L2, inductor_values_t::L3, inductor_values_t::L4, inductor_values_t::L5, inductor_values_t::L6, inductor_values_t::L7, led_wr_str(), SW, type, work_int, work_str, and work_str_2.
Referenced by btn_push(), button_proc(), button_proc_test(), lcd_prep(), main(), show_pwr(), show_reset(), and tune().
lcd_prep()
void lcd_prep (void)
Definition at line 702 of file main.c.
                {
    CLEAR_WDT();
    if ((type == 4) || (type == 5)) { // 128*64 OLED
        if (lcd_prep_short == 0) {
            led_wr_str(0, 22, "ATU-100", 7);
            led_wr_str(2, 6, "EXT board", 9);
            led_wr_str(4, 16, "by N7DDC", 8);
            led_wr_str(6, 4, "FW ver 3.2", 10);
            CLEAR_WDT();
            Delay_ms(600);
            CLEAR_WDT();
            Delay_ms(500);
            CLEAR_WDT();
            led_wr_str(0, 16, "        ", 8);
            led_wr_str(2, 4, "          ", 10);
            led_wr_str(4, 16, "        ", 8);
            led_wr_str(6, 4, "          ", 10);
        }
        Delay_ms(150);
        if (P_High == 1) led_wr_str(0, 16, "PWR=  0W", 8);
        else led_wr_str(0, 16, "PWR=0.0W", 8);
        led_wr_str(2, 16, "SWR=0.00", 8);
        if (Auto) led_wr_str(0, 16 + 8 * 12, ".", 1);
    } else if (type != 0) { // 1602 LCD & 128*32 OLED
        if (lcd_prep_short == 0) {
            led_wr_str(0, 4, "ATU-100", 7);
            led_wr_str(1, 3, "EXT board", 9);
            CLEAR_WDT();
            Delay_ms(700);
            CLEAR_WDT();
            Delay_ms(500);
            CLEAR_WDT();
            led_wr_str(0, 4, "by N7DDC", 8);
            led_wr_str(1, 3, "FW ver 3.2", 10);
            CLEAR_WDT();
            Delay_ms(600);
            CLEAR_WDT();
            Delay_ms(500);
            CLEAR_WDT();
            led_wr_str(0, 4, "        ", 8);
            led_wr_str(1, 3, "          ", 10);
        }
        Delay_ms(150);
        if (P_High == 1) {
            led_wr_str(0, 0, "PWR=  0W", 8);
        } else {
            led_wr_str(0, 0, "PWR=0.0W", 8);
        }
        led_wr_str(1, 0, "SWR=0.00", 8);
        if (Auto) {
            led_wr_str(0, 8, ".", 1);
        }
    }
    CLEAR_WDT();
    lcd_ind();
    return;
}
References Auto, CLEAR_WDT, lcd_ind(), lcd_prep_short, led_wr_str(), P_High, and type.
Referenced by main(), and test_init().
lcd_pwr()
void lcd_pwr (void)
Definition at line 989 of file main.c.
               {
    int p = 0;
    char peak_cnt;
    int delta = Auto_delta - 100;
    char cnt;
    int SWR_fixed;
    PWR = 0;
    CLEAR_WDT();
    if ((dysp == 0) && (Relay_off == 1)) {
        get_pwr();
        if (PWR >= 10) {
            set_ind(ind.byte);
            set_cap(cap.byte);
            set_sw(SW);
            dysp = 1;
            display_on(); // display ON
            dysp_cnt = Dysp_delay * dysp_cnt_mult;
        }
        return;
    }
    // peak detector
    cnt = 120;
    for (peak_cnt = 0; peak_cnt < cnt; peak_cnt++) {
        if ((PORTBbits.RB1 == 0) || (PORTBbits.RB2 == 0) || ((PORTBbits.RB0 == 0) && tune_btn_release)) {
            button_delay();
            if (but == 1) {
                but = 0;
                return;
            }
        }
        get_pwr();
        if (PWR > p) {
            p = PWR;
            SWR_fixed = SWR;
        }
        Delay_ms(3);
    }
    CLEAR_WDT();
    /* round to 1W if more than 100W... */
    if (p >= 100) {
        p = (p + 5) / 10;
        p *= 10;
    }
    Power = p;
    if (Power < 10) SWR_fixed = 0;
    lcd_swr(SWR_fixed);
    if (Power >= 10 & Dysp_delay > 0) {
        dysp_cnt = Dysp_delay * dysp_cnt_mult;
    }
    if (Auto && SWR_fixed >= Auto_delta && ((SWR_fixed > SWR_fixed_old && (SWR_fixed - SWR_fixed_old) > delta) || (SWR_fixed < SWR_fixed_old && (SWR_fixed_old - SWR_fixed) > delta) || SWR_fixed_old == 999)) {
        Soft_tune = 1;
    }
    if ((PORTBbits.RB1 == 0) || (PORTBbits.RB2 == 0) || ((PORTBbits.RB0 == 0) && (tune_btn_release))) {
        button_delay();
        if (but == 1) {
            but = 0;
            return;
        }
    } // Fast return if button pressed
    show_pwr(Power, SWR_fixed);
    if ((PORTBbits.RB1 == 0) || (PORTBbits.RB2 == 0) || ((PORTBbits.RB0 == 0) && (tune_btn_release))) {
        button_delay();
        if (but == 1) {
            but = 0;
            return;
        }
    }
    CLEAR_WDT();
    if (Overload == 1) {
        if (type == 4 || type == 5) { // 128*64 OLED
            led_wr_str(2, 16, "        ", 8);
            delay_ms(100);
            led_wr_str(2, 16, "OVERLOAD", 8);
            delay_ms(500);
            CLEAR_WDT();
            led_wr_str(2, 16, "        ", 8);
            delay_ms(300);
            CLEAR_WDT();
            led_wr_str(2, 16, "OVERLOAD", 8);
            delay_ms(500);
            CLEAR_WDT();
            led_wr_str(2, 16, "        ", 8);
            delay_ms(300);
            CLEAR_WDT();
            led_wr_str(2, 16, "OVERLOAD", 8);
            delay_ms(500);
            CLEAR_WDT();
            led_wr_str(2, 16, "        ", 8);
            delay_ms(100);
            led_wr_str(2, 16, "SWR=    ", 8);
        } else if (type != 0) { // 1602  & 128*32
            led_wr_str(1, 0, "        ", 8);
            delay_ms(100);
            led_wr_str(1, 0, "OVERLOAD", 8);
            delay_ms(500);
            CLEAR_WDT();
            led_wr_str(1, 0, "        ", 8);
            delay_ms(300);
            CLEAR_WDT();
            led_wr_str(1, 0, "OVERLOAD", 8);
            delay_ms(500);
            CLEAR_WDT();
            led_wr_str(1, 0, "        ", 8);
            delay_ms(300);
            CLEAR_WDT();
            led_wr_str(1, 0, "OVERLOAD", 8);
            delay_ms(500);
            CLEAR_WDT();
            led_wr_str(1, 0, "        ", 8);
            delay_ms(100);
            led_wr_str(1, 0, "SWR=    ", 8);
        }
        CLEAR_WDT();
        SWR_old = 10000;
        lcd_swr(SWR_fixed);
    }
    return;
}
References Auto, Auto_delta, but, button_delay(), bit_byte_t::byte, cap, CLEAR_WDT, display_on(), dysp, dysp_cnt, dysp_cnt_mult, Dysp_delay, get_pwr(), ind, lcd_swr(), led_wr_str(), Overload, Power, PWR, Relay_off, set_cap(), set_ind(), set_sw(), show_pwr(), Soft_tune, SW, SWR, SWR_fixed_old, SWR_old, tune_btn_release, and type.
Referenced by btn_push(), button_proc(), button_proc_test(), main(), and show_reset().
lcd_swr()
void lcd_swr (int swr)
Definition at line 767 of file main.c.
                      {
    CLEAR_WDT();
    if (swr != SWR_old) {
        SWR_old = swr;
        if (SWR == 0) { // Low power
            if ((type == 4) || (type == 5)) {               /* 128x64 OLED */
                led_wr_str(2, 16 + 4 * 12, "0.00", 4);
            } else if (type != 0) {                         /* 1602 & 128x32 OLED */
                led_wr_str(1, 4, "0.00", 4);
            } else if (type == 0) {                         /* Use a 2-color (green/red) common-anode LED */
                LATBbits.LATB6 = 1;
                LATBbits.LATB7 = 1;
            }
            SWR_old = 0;
        } else {
            IntToStr(swr, work_str);
            work_str_2[0] = work_str[3];
            work_str_2[1] = '.';
            work_str_2[2] = work_str[4];
            work_str_2[3] = work_str[5];
            if ((type == 4) || (type == 5)) {
                led_wr_str(2, 16 + 4 * 12, work_str_2, 4);
            } else if (type != 0) {
                led_wr_str(1, 4, work_str_2, 4);
            } else if (type == 0) {
                if (swr <= 150) {                           /* Green */
                    LATBbits.LATB6 = 0;
                    LATBbits.LATB7 = 1;
                } else if (swr <= 250) {                    /* Orange */
                    PORTBbits.RB6 = 0;
                    PORTBbits.RB7 = 0;
                } else {                                    /* Red */
                    PORTBbits.RB6 = 1;
                    PORTBbits.RB7 = 0;
                }
            }
        }
    }
    CLEAR_WDT();
    return;
}
References CLEAR_WDT, led_wr_str(), SWR, SWR_old, type, work_str, and work_str_2.
Referenced by lcd_pwr().
set_cap()
void set_cap (uint8_t Cap)
Definition at line 408 of file main.h.
{
    bit_byte_t bbCap;
    bbCap.byte = Cap;
    Cap_10 = bbCap.B0;
    Cap_22 = bbCap.B1;
    Cap_47 = bbCap.B2;
    Cap_100 = bbCap.B3;
    Cap_220 = bbCap.B4;
    Cap_470 = bbCap.B5;
    Cap_1000 = bbCap.B6;
    Delay_ms(relay_delay_ms);
}
References bit_byte_t::byte, Cap_10, Cap_100, Cap_1000, Cap_22, Cap_220, Cap_47, Cap_470, and relay_delay_ms.
Referenced by atu_reset(), button_proc(), button_proc_test(), coarse_cap(), coarse_tune(), lcd_pwr(), main(), sharp_cap(), and sub_tune().
set_ind()
void set_ind (uint8_t Ind)
Definition at line 382 of file main.h.
{
    bit_byte_t bbInd;
    bbInd.byte = Ind;
    if (L_invert == 0) {
        Ind_005 = bbInd.B0;
        Ind_011 = bbInd.B1;
        Ind_022 = bbInd.B2;
        Ind_045 = bbInd.B3;
        Ind_1 = bbInd.B4;
        Ind_22 = bbInd.B5;
        Ind_45 = bbInd.B6;
    } else {
        Ind_005 = ~bbInd.B0;
        Ind_011 = ~bbInd.B1;
        Ind_022 = ~bbInd.B2;
        Ind_045 = ~bbInd.B3;
        Ind_1 = ~bbInd.B4;
        Ind_22 = ~bbInd.B5;
        Ind_45 = ~bbInd.B6;
    }
    Delay_ms(relay_delay_ms);
}
References bit_byte_t::byte, Ind_005, Ind_011, Ind_022, Ind_045, Ind_1, Ind_22, Ind_45, L_invert, and relay_delay_ms.
Referenced by atu_reset(), button_proc(), button_proc_test(), coarse_tune(), lcd_pwr(), main(), sharp_ind(), and sub_tune().
set_sw()
void set_sw (char SW)
Set the state of the switch.
This sets the state (direction) of the switch (relay) used to measure forward/reverse power and SWR.
Parameters
[in] SW The desired direction:
0 – IN
1 – OUT
Definition at line 433 of file main.h.
                     { // 0 - IN,  1 - OUT
    Cap_sw = SW;
    Delay_ms(relay_delay_ms);
}
References Cap_sw, relay_delay_ms, and SW.
Referenced by button_proc(), button_proc_test(), lcd_pwr(), main(), show_reset(), sub_tune(), and test_init().
sharp_cap()
void sharp_cap ()
Definition at line 547 of file main.h.
                 {
    uint8_t range;
    uint8_t count;
    uint8_t max_range;
    uint8_t min_range;
    int min_SWR;
    range = step_cap * C_mult;
    max_range = cap.byte + range;
    if (max_range > 32 * C_mult - 1) {
        max_range = 32 * C_mult - 1;
    }
    if (cap.byte > range) {
        min_range = cap.byte - range;
    } else {
        min_range = 0;
    }
    cap.byte = min_range;
    set_cap(cap.byte);
    get_swr();
    if (SWR == 0) {
        return;
    }
    min_SWR = SWR;
    for (count = min_range + C_mult; count <= max_range; count += C_mult) {
        set_cap(count);
        get_swr();
        if (SWR == 0) {
            return;
        }
        if (SWR >= min_SWR) {
            Delay_ms(10);
            get_swr();
        }
        if (SWR >= min_SWR) {
            Delay_ms(10);
            get_swr();
        }
        if (SWR < min_SWR) {
            min_SWR = SWR;
            cap.byte = count;
            if (SWR < 120) {
                break;
            }
        } else {
            break;
        }
    }
    set_cap(cap.byte);
    return;
}
References bit_byte_t::byte, C_mult, cap, get_swr(), set_cap(), step_cap, and SWR.
Referenced by sub_tune(), and tune().
sharp_ind()
void sharp_ind ()
Definition at line 611 of file main.h.
                 {
    uint8_t range;
    uint8_t count;
    uint8_t max_range;
    uint8_t min_range;
    int min_SWR;
    range = step_ind * L_mult;
    max_range = ind.byte + range;
    if (max_range > 32 * L_mult - 1) {
        max_range = 32 * L_mult - 1;
    }
    if (ind.byte > range) {
        min_range = ind.byte - range;
    } else {
        min_range = 0;
    }
    ind.byte = min_range;
    set_ind(ind.byte);
    get_swr();
    if (SWR == 0) {
        return;
    }
    min_SWR = SWR;
    for (count = min_range + L_mult; count <= max_range; count += L_mult) {
        set_ind(count);
        get_swr();
        if (SWR == 0) {
            return;
        }
        if (SWR >= min_SWR) {
            Delay_ms(10);
            get_swr();
        }
        if (SWR >= min_SWR) {
            Delay_ms(10);
            get_swr();
        }
        if (SWR < min_SWR) {
            min_SWR = SWR;
            ind.byte = count;
            if (SWR < 120) {
                break;
            }
        } else {
            break;
        }
    }
    set_ind(ind.byte);
    return;
}
References bit_byte_t::byte, get_swr(), ind, L_mult, set_ind(), step_ind, and SWR.
Referenced by sub_tune(), and tune().
show_loss()
void show_loss (void)
Definition at line 1351 of file main.c.
                     {
    IntToStr(Fid_loss, work_str);
    if (Fid_loss >= 10) {
        work_str_2[0] = work_str[4];
    } else {
        work_str_2[0] = '0';
    }
    work_str_2[1] = '.';
    work_str_2[2] = work_str[5];
    if ((type == 4) || (type == 5)) {           /* 128x64 OLED display */
        led_wr_str(4, 6, work_str_2, 3);
    } else if (type != 0) {                     /* 16x2 LCD or 128x32 OLED display */
        led_wr_str(1, 0, work_str_2, 3);
    }
    return;
}
References Fid_loss, led_wr_str(), type, work_str, and work_str_2.
Referenced by main().
show_pwr()
void show_pwr (int Power, int SWR)
Definition at line 821 of file main.c.
{
    int p_ant;
    int eff;
    float a = 100.0;
    float b;
    CLEAR_WDT();
    if ((Test == 0) && (Loss_ind == 1) && (Power >= 10)) {
        if (Loss_mode == 0) { // prepare
            if (type == 4 || type == 5) { // 128*64 OLED
                if (P_High == 1) led_wr_str(4, 16, "ANT=  0W", 8);
                else led_wr_str(4, 16, "ANT=0.0W", 8);
                led_wr_str(6, 16, "EFF=  0%", 8);
            } else if (type == 2 || type == 3) { // 128*32 OLED
                if (P_High == 1) led_wr_str(0, 9, "ANT=  0W", 8);
                else led_wr_str(0, 9, "ANT=0.0W", 8);
                led_wr_str(1, 9, "EFF=  0%", 8);
            } else if (type == 1) { // 1602 LCD
                if (P_High == 1) led_wr_str(0, 9, "AN=  0W", 7);
                else led_wr_str(0, 9, "AN=0.0W", 7);
                led_wr_str(1, 9, "EFF= 0%", 7);
            }
        }
        Loss_mode = 1;
    } else {
        if (Loss_mode == 1) {
            lcd_ind();
        }
        Loss_mode = 0;
    }
    CLEAR_WDT();
    if (Power != Power_old) {
        Power_old = Power;
        if (P_High == 0) {
            if (Power >= 100) {                                         // > 10W
                Power += 5;                                             // rounding to 1W
                IntToStr(Power, work_str);
                work_str_2[0] = work_str[2];
                work_str_2[1] = work_str[3];
                work_str_2[2] = work_str[4];
                work_str_2[3] = 'W';
            } else {
                IntToStr(Power, work_str);
                if (work_str[4] != ' ') {
                    work_str_2[0] = work_str[4];
                } else {
                    work_str_2[0] = '0';
                }
                work_str_2[1] = '.';
                if (work_str[5] != ' ') {
                    work_str_2[2] = work_str[5];
                } else {
                    work_str_2[2] = '0';
                }
                work_str_2[3] = 'W';
            }
        } else {                                                        // High Power
            if (Power < 999) {                                          // 0W - 999W
                IntToStr(Power, work_str);
                work_str_2[0] = work_str[3];
                work_str_2[1] = work_str[4];
                work_str_2[2] = work_str[5];
                work_str_2[3] = 'W';
            } else {
                IntToStr(Power, work_str);
                work_str_2[0] = work_str[2];
                work_str_2[1] = work_str[3];
                work_str_2[2] = work_str[4];
                work_str_2[3] = work_str[5];
            }
        }
        if ((type == 4) || (type == 5)) {                               /* 128x64 OLED display */
            led_wr_str(0, 16 + 4 * 12, work_str_2, 4);
        } else if (type != 0) {                                         /* 16x2 character LCD & 128x32 OLED display */
            led_wr_str(0, 4, work_str_2, 4);
        }
        CLEAR_WDT();
        /* Loss indication */
        if (Loss_mode == 1) {
            if (ind.byte == 0 && cap.byte == 0) {
                swr_a = SWR;
            }
            a = 1.0 / ((swr_a / 100.0 + 100.0 / swr_a) * Fid_loss / 10.0 * 0.115 + 1.0);    /* Feed line loss */
            b = 4.0 / (2.0 + SWR / 100.0 + 100.0 / SWR);                                    /* SWR loss */
            if (a >= 1.0) {
                a = 1.0;
            }
            if (b >= 1.0) {
                b = 1.0;
            }
            p_ant = Power * a * b;
            eff = a * b * 100;
            if (eff >= 100) {
                eff = 99;
            }
            if (P_High == 0) {
                if (p_ant >= 100) {                                                         /* > 10W */
                    p_ant += 5;                                                             /* rounding to 1W */
                    IntToStr(p_ant, work_str);
                    work_str_2[0] = work_str[2];
                    work_str_2[1] = work_str[3];
                    work_str_2[2] = work_str[4];
                    work_str_2[3] = 'W';
                } else {
                    IntToStr(p_ant, work_str);
                    if (work_str[4] != ' ') {
                        work_str_2[0] = work_str[4];
                    } else {
                        work_str_2[0] = '0';
                    }
                    work_str_2[1] = '.';
                    if (work_str[5] != ' ') {
                        work_str_2[2] = work_str[5];
                    } else {
                        work_str_2[2] = '0';
                    }
                    work_str_2[3] = 'W';
                }
            } else {                                                                        /* High Power */
                if (p_ant < 999) {                                                          /* 0 - 1500 Watts */
                    IntToStr(p_ant, work_str);
                    work_str_2[0] = work_str[3];
                    work_str_2[1] = work_str[4];
                    work_str_2[2] = work_str[5];
                    work_str_2[3] = 'W';
                } else {
                    IntToStr(p_ant, work_str);
                    work_str_2[0] = work_str[2];
                    work_str_2[1] = work_str[3];
                    work_str_2[2] = work_str[4];
                    work_str_2[3] = work_str[5];
                }
            }
            if (type == 4 || type == 5) led_wr_str(4, 16 + 4 * 12, work_str_2, 4); // 128*64 OLED
            else if (type == 2 || type == 3) led_wr_str(0, 13, work_str_2, 4); // 128*32
            else if (type != 0) led_wr_str(0, 12, work_str_2, 4); // 1602
            IntToStr(eff, work_str);
            work_str_2[0] = work_str[4];
            work_str_2[1] = work_str[5];
            if (type == 4 || type == 5) led_wr_str(6, 16 + 5 * 12, work_str_2, 2);
            else if (type == 2 || type == 3) led_wr_str(1, 14, work_str_2, 2);
            else if (type == 1) led_wr_str(1, 13, work_str_2, 2);
        }
    }
    CLEAR_WDT();
    return;
}
References bit_byte_t::byte, cap, CLEAR_WDT, Fid_loss, ind, lcd_ind(), led_wr_str(), Loss_ind, Loss_mode, P_High, Power, Power_old, SWR, swr_a, Test, type, work_str, and work_str_2.
Referenced by get_swr(), and lcd_pwr().
show_reset()
void show_reset (void)
Definition at line 613 of file main.c.
                  {
    atu_reset();
    SW = 1;
    set_sw(SW);
    EEPROM_Write(255, 0);
    EEPROM_Write(254, 0);
    EEPROM_Write(253, 1);
    EEPROM_Write(252, 0);
    EEPROM_Write(251, 0);
    lcd_ind();
    Loss_mode = 0;
    p_Tx = 0;
    n_Tx = 1;
    SWR = 0;
    PWR = 0;
    SWR_fixed_old = 0;
    if ((type == 4) || (type == 5)) {                                   // 128*64 OLED
        led_wr_str(2, 16, "RESET   ", 8);
        CLEAR_WDT();
        delay_ms(600);
        led_wr_str(2, 16, "SWR=0.00", 8);
        CLEAR_WDT();
    } else if (type != 0) {                                             // 1602 LCD & 128*32 OLED
        led_wr_str(1, 0, "RESET   ", 8);
        CLEAR_WDT();
        delay_ms(600);
        led_wr_str(1, 0, "SWR=0.00", 8);
        CLEAR_WDT();
    } else {
        LATBbits.LATB6 = 1;
        LATBbits.LATB7 = 1;
    }
    SWR_old = 10000;
    Power_old = 10000;
    lcd_pwr();
    return;
}
References atu_reset(), CLEAR_WDT, lcd_ind(), lcd_pwr(), led_wr_str(), Loss_mode, n_Tx, p_Tx, Power_old, PWR, set_sw(), SW, SWR, SWR_fixed_old, SWR_old, and type.
Referenced by button_proc(), and get_swr().
sub_tune()
void sub_tune (void)
Definition at line 675 of file main.h.
                {
    int swr_mem, ind_mem, cap_mem;
    swr_mem = SWR;
    coarse_tune();
    if (SWR == 0) {
        atu_reset();
        return;
    }
    get_swr();
    if (SWR < 120) return;
    sharp_ind();
    if (SWR == 0) {
        atu_reset();
        return;
    }
    get_swr();
    if (SWR < 120) return;
    sharp_cap();
    if (SWR == 0) {
        atu_reset();
        return;
    }
    get_swr();
    if (SWR < 120) {
        return;
    }
    if ((SWR < 200) && (SWR < swr_mem) && ((swr_mem - SWR) > 100)) {
        return;
    }
    swr_mem = SWR;
    ind_mem = ind.byte;
    cap_mem = cap.byte;
    if (SW == 1) {
        SW = 0;
    } else {
        SW = 1;
    }
    atu_reset();
    set_sw(SW);
    Delay_ms(50);
    get_swr();
    if (SWR < 120) {
        return;
    }
    coarse_tune();
    if (SWR == 0) {
        atu_reset();
        return;
    }
    get_swr();
    if (SWR < 120) {
        return;
    }
    sharp_ind();
    if (SWR == 0) {
        atu_reset();
        return;
    }
    get_swr();
    if (SWR < 120) {
        return;
    }
    sharp_cap();
    if (SWR == 0) {
        atu_reset();
        return;
    }
    get_swr();
    if (SWR < 120) {
        return;
    }
    if (SWR > swr_mem) {
        if (SW == 1) {
            SW = 0;
        } else {
            SW = 1;
        }
        set_sw(SW);
        ind.byte = ind_mem;
        cap.byte = cap_mem;
        set_ind(ind.byte);
        set_cap(cap.byte);
        SWR = swr_mem;
    }
    CLEAR_WDT();
    return;
}
References atu_reset(), bit_byte_t::byte, cap, cap_mem, CLEAR_WDT, coarse_tune(), get_swr(), ind, ind_mem, set_cap(), set_ind(), set_sw(), sharp_cap(), sharp_ind(), SW, and SWR.
Referenced by tune().
test_init()
void test_init (void)
Definition at line 1247 of file main.c.
                     { // Test mode
    if ((type == 4) || (type == 5)) {           // 128*64 OLED
        led_wr_str(0, 10, "TEST MODE", 9);
    } else if (type != 0) {                     // 1602 LCD or 128*32 OLED
        led_wr_str(0, 3, "TEST MODE", 9);
    }
    CLEAR_WDT();
    Delay_ms(500);
    CLEAR_WDT();
    Delay_ms(500);
    CLEAR_WDT();
    Delay_ms(500);
    CLEAR_WDT();
    Delay_ms(500);
    CLEAR_WDT();
    if ((type == 4) || (type == 5)) {           // 128*64 OLED
        led_wr_str(0, 10, "         ", 9);
    } else if (type != 0) {                     // 1602 LCD  or 128*32 OLED
        led_wr_str(0, 3, "         ", 9);
    }
    atu_reset();
    SW = 1;                                     // C to OUT
    set_sw(SW);
    EEPROM_Write(255, cap.byte);
    EEPROM_Write(254, ind.byte);
    EEPROM_Write(253, SW);
    if (type == 4 || type == 5) // 128*64 OLED
        led_wr_str(0, 16 + 12 * 8, "l", 1);
    else if (type != 0) // 1602 LCD or 128*32 OLED
        led_wr_str(0, 8, "l", 1);
    lcd_prep_short = 1;
    lcd_prep();
    return;
}
References atu_reset(), bit_byte_t::byte, cap, CLEAR_WDT, ind, lcd_prep(), lcd_prep_short, led_wr_str(), set_sw(), SW, and type.
Referenced by main().
tune()
void tune (void)
Definition at line 789 of file main.h.
            {
#if 0
    int swr_mem;
    int ind_mem;
    int cap_mem;
    int sw_mem;
#endif
    CLEAR_WDT();
    p_cnt = 0;
    P_max = 0;
    rready = 0;
    /* Get the SWR to start the tuning process... */
    get_swr();
    if (SWR <= SWR_NO_TUNE_UNDER) {     /* If the SWR is already low enough, don't attempt to tune */
        return;
    }
    atu_reset();
    if (Loss_ind == 0) {
        lcd_ind();
    }
    Delay_ms(50);
    get_swr();
    swr_a = SWR;
    if (SWR <= SWR_NO_TUNE_UNDER) {     /* If the SWR is already low enough, don't attempt to tune */
        return;
    }
    if ((max_swr > SWR_NO_TUNE_UNDER) && (SWR > max_swr)) {     /* If the SWR exceeds the max, don't attempt tuning */
        return;
    }
    sub_tune();
    if (SWR == 0) {
        atu_reset();
        return;
    }
    if (SWR < SWR_TUNE_TARGET) {
        return;
    }
    if ((C_q == 5) && (L_q == 5)) {
        return;
    }
    if (L_q > 5) {
        step_ind = L_mult;
        L_mult = 1;
        sharp_ind();
    }
    if (SWR < SWR_TUNE_TARGET) {
        return;
    }
    if (C_q > 5) {
        step_cap = C_mult; // = C_mult
        C_mult = 1;
        sharp_cap();
    }
    if (L_q == 5) {
        L_mult = 1;
    } else if (L_q == 6) {
        L_mult = 2;
    } else if (L_q == 7) {
        L_mult = 4;
    }
    if (C_q == 5) {
        C_mult = 1;
    } else if (C_q == 6) {
        C_mult = 2;
    } else if (C_q == 7) {
        C_mult = 4;
    }
    CLEAR_WDT();
    return;
}
References atu_reset(), C_mult, C_q, cap_mem, CLEAR_WDT, get_swr(), ind_mem, L_mult, L_q, lcd_ind(), Loss_ind, max_swr, p_cnt, P_max, rready, sharp_cap(), sharp_ind(), step_cap, step_ind, sub_tune(), SWR, swr_a, SWR_NO_TUNE_UNDER, and SWR_TUNE_TARGET.
Referenced by btn_push().
Variable Definitions
C_linear
char C_linear = 0 static
Definition at line 58 of file main.h.
Referenced by coarse_cap(), and init_runtime_data_from_eeprom().
C_mult
char C_mult = 1 static
Definition at line 64 of file main.h.
Referenced by coarse_cap(), main(), sharp_cap(), and tune().
C_q
char C_q = 7 static
Definition at line 60 of file main.h.
Referenced by init_runtime_data_from_eeprom(), main(), and tune().
cap
bit_byte_t cap extern
Definition at line 67 of file main.c.
Referenced by atu_reset(), btn_push(), button_proc(), button_proc_test(), coarse_cap(), coarse_tune(), lcd_ind(), lcd_pwr(), main(), sharp_cap(), show_pwr(), sub_tune(), and test_init().
D_correction
char D_correction = 1 static
Definition at line 61 of file main.h.
Referenced by get_pwr(), and init_runtime_data_from_eeprom().
ind
bit_byte_t ind extern
Definition at line 66 of file main.c.
Referenced by atu_reset(), btn_push(), button_proc(), button_proc_test(), coarse_tune(), lcd_ind(), lcd_pwr(), main(), sharp_ind(), show_pwr(), sub_tune(), and test_init().
K_Mult
char K_Mult = 32 static
Definition at line 66 of file main.h.
Referenced by get_pwr(), and init_runtime_data_from_eeprom().
L_invert
char L_invert = 0 static
Definition at line 62 of file main.h.
Referenced by button_proc(), init_runtime_data_from_eeprom(), main(), and set_ind().
L_linear
char L_linear = 0 static
Definition at line 57 of file main.h.
Referenced by coarse_tune(), and init_runtime_data_from_eeprom().
L_mult
char L_mult = 1 static
Definition at line 63 of file main.h.
Referenced by button_proc_test(), coarse_tune(), main(), sharp_ind(), and tune().
L_q
char L_q = 7 static
Definition at line 59 of file main.h.
Referenced by init_runtime_data_from_eeprom(), main(), and tune().
Loss_ind
char Loss_ind = 0 static
Definition at line 68 of file main.h.
Referenced by btn_push(), init_runtime_data_from_eeprom(), show_pwr(), and tune().
max_for_start
int max_for_start static
Definition at line 72 of file main.h.
Referenced by get_swr(), and init_runtime_data_from_eeprom().
max_swr
int max_swr static
Definition at line 73 of file main.h.
Referenced by init_runtime_data_from_eeprom(), and tune().
min_for_start
int min_for_start static
Definition at line 71 of file main.h.
Referenced by get_swr(), and init_runtime_data_from_eeprom().
Overload
char Overload = 0 static
Definition at line 67 of file main.h.
Referenced by get_forward(), and lcd_pwr().
p_cnt
char p_cnt = 0
Definition at line 80 of file main.h.
Referenced by get_swr(), and tune().
P_High
char P_High = 0 static
Definition at line 65 of file main.h.
Referenced by get_pwr(), init_runtime_data_from_eeprom(), lcd_prep(), and show_pwr().
P_max
int P_max
Definition at line 77 of file main.h.
Referenced by get_swr(), and tune().
PWR
int PWR
Definition at line 76 of file main.h.
Referenced by get_pwr(), get_swr(), lcd_pwr(), and show_reset().
relay_delay_ms
int relay_delay_ms extern
Definition at line 166 of file main.c.
Referenced by atu_reset(), init_runtime_data_from_eeprom(), set_cap(), set_ind(), and set_sw().
Relay_off
char Relay_off = 0 static
Definition at line 69 of file main.h.
Referenced by button_proc(), init_runtime_data_from_eeprom(), lcd_pwr(), and main().
rready
char rready = 0
Definition at line 79 of file main.h.
Referenced by get_swr(), and tune().
step_cap
char step_cap = 0 static
Definition at line 55 of file main.h.
Referenced by coarse_cap(), coarse_tune(), sharp_cap(), and tune().
step_ind
char step_ind = 0 static
Definition at line 56 of file main.h.
Referenced by coarse_tune(), sharp_ind(), and tune().
SW
char SW = 0 static
Definition at line 54 of file main.h.
Referenced by btn_push(), button_proc(), button_proc_test(), lcd_ind(), lcd_pwr(), main(), set_sw(), show_reset(), sub_tune(), and test_init().
SWR
int SWR extern
Holds the current SWR.
The current SWR is represented as an integer value following the following formula: \(SWR * 100 \)
Definition at line 165 of file main.c.
Referenced by btn_push(), coarse_cap(), coarse_tune(), get_pwr(), get_swr(), lcd_pwr(), lcd_swr(), sharp_cap(), sharp_ind(), show_pwr(), show_reset(), sub_tune(), and tune().
swr_a
int swr_a
Definition at line 78 of file main.h.
Referenced by btn_push(), main(), show_pwr(), and tune().