ATU100_PIC16F1938: mcc_generated_files/adc.h File Reference
adc.h File Reference
#include <xc.h>
#include <stdint.h>
#include <stdbool.h>
Type Definitions
typedef uint16_t adc_result_t
Enumerations
enum adc_channel_t {
swr_bridge_rev = 0x0 ,
swr_bridge_fwd = 0x1 ,
channel_Temp = 0x1D ,
channel_DAC = 0x1E ,
channel_FVR = 0x1F
}
Classes
struct adc_sync_double_result_t
Function Declarations
void ADC_Initialize (void)
void ADC_SelectChannel (adc_channel_t channel)
void ADC_StartConversion (void)
bool ADC_IsConversionDone (void)
adc_result_t ADC_GetConversionResult (void)
adc_result_t ADC_GetConversion (adc_channel_t channel)
void ADC_TemperatureAcquisitionDelay (void)
void ADC_ISR (void)
void ADC_SetInterruptHandler (void(*InterruptHandler)(void))
void ADC_DefaultInterruptHandler (void)
Variable Declarations
void(* ADC_InterruptHandler)(void)
Type Definitions
adc_result_t
typedef uint16_t adc_result_t
ADC Generated Driver API Header File
@Company Microchip Technology Inc.
@File Name adc.h
@Summary This is the generated header file for the ADC driver using PIC10 / PIC12 / PIC16 / PIC18 MCUs
@Description This header file provides APIs for driver for ADC. Generation Information : Product Revision : PIC10 / PIC12 / PIC16 / PIC18 MCUs - 1.81.7 Device : PIC16F1938 Driver Version : 2.02 The generated drivers are tested against the following: Compiler : XC8 2.31 and above MPLAB : MPLAB X 5.45 Section: Included Files Section: Data Types Definitions result size of an A/D conversion
Definition at line 72 of file adc.h.
Enumerations
adc_channel_t
enum adc_channel_t
ADC Channel Definition
@Summary Defines the channels available for conversion.
@Description This routine defines the channels that are available for the module to use.
Remarks: None
Enumerator
swr_bridge_rev
swr_bridge_fwd
channel_Temp
channel_DAC
channel_FVR
Definition at line 95 of file adc.h.
{
    swr_bridge_rev =  0x0,
    swr_bridge_fwd =  0x1,
    channel_Temp =  0x1D,
    channel_DAC =  0x1E,
    channel_FVR =  0x1F
} adc_channel_t;
Data Structure Documentation
adc_sync_double_result_t
struct adc_sync_double_result_t
result type of a Double ADC conversion
Definition at line 77 of file adc.h.
Data Fields
adc_result_t adcResult1
adc_result_t adcResult2
Function Definitions
ADC_DefaultInterruptHandler()
void ADC_DefaultInterruptHandler (void)
@Summary Default Timer Interrupt Handler
@Description This is the default Interrupt Handler function
@Preconditions Initialize the ADC module with interrupt before calling this isr.
@Param None
@Returns None
Definition at line 160 of file adc.c.
{
    // add your ADC interrupt custom code
    // or set custom function using ADC_SetInterruptHandler()
}
Referenced by ADC_Initialize().
ADC_GetConversion()
adc_result_t ADC_GetConversion (adc_channel_t channel)
@Summary Returns the ADC conversion value also allows selection of a channel for conversion.
@Description This routine is used to select desired channel for conversion and to get the analog to digital converted value.
@Preconditions ADC_Initialize() function should have been called before calling this function.
@Returns Returns the converted value.
@Param Pass in required channel number. "For available channel refer to enum under adc.h file"
@Example uint16_t convertedValue;
ADC_Initialize();
conversion = ADC_GetConversion(AN1_Channel);
Definition at line 117 of file adc.c.
{
    // select the A/D channel
    ADCON0bits.CHS = channel;
    // Turn on the ADC module
    ADCON0bits.ADON = 1;
    // Acquisition time delay
    __delay_us(ACQ_US_DELAY);
    // Start the conversion
    ADCON0bits.GO_nDONE = 1;
    // Wait for the conversion to finish
    while (ADCON0bits.GO_nDONE)
    {
    }
    // Conversion finished, return the result
    return ((adc_result_t)((ADRESH << 8) + ADRESL));
}
References ACQ_US_DELAY.
ADC_GetConversionResult()
adc_result_t ADC_GetConversionResult (void)
@Summary Returns the ADC conversion value.
@Description This routine is used to get the analog to digital converted value. This routine gets converted values from the channel specified.
@Preconditions This routine returns the conversion value only after the conversion is complete. Completion status can be checked using ADC_IsConversionDone() routine.
@Returns Returns the converted value.
@Param None
@Example uint16_t convertedValue;
ADC_Initialize(); ADC_StartConversion();
while(ADC_IsConversionDone());
convertedValue = ADC_GetConversionResult();
Definition at line 111 of file adc.c.
{
    // Conversion finished, return the result
    return ((adc_result_t)((ADRESH << 8) + ADRESL));
}
ADC_Initialize()
void ADC_Initialize (void)
Section: ADC Module APIs @Summary Initializes the ADC
@Description This routine initializes the Initializes the ADC. This routine must be called before any other ADC routine is called. This routine should only be called once during system initialization.
@Preconditions None
@Param None
@Returns None
@Comment
@Example uint16_t convertedValue;
ADC_Initialize(); convertedValue = ADC_GetConversionResult();
Section: ADC Module APIs
Definition at line 67 of file adc.c.
{
    // set the ADC to the options selected in the User Interface
    // ADFM left; ADNREF VSS; ADPREF FVR; ADCS FOSC/16;
    ADCON1 = 0x53;
    // ADRESL 0;
    ADRESL = 0x00;
    // ADRESH 0;
    ADRESH = 0x00;
    // GO_nDONE stop; ADON enabled; CHS AN0;
    ADCON0 = 0x01;
    // Enabling ADC interrupt.
    PIE1bits.ADIE = 1;
    // Set Default Interrupt Handler
    ADC_SetInterruptHandler(ADC_DefaultInterruptHandler);
}
References ADC_DefaultInterruptHandler(), and ADC_SetInterruptHandler().
Referenced by SYSTEM_Initialize().
ADC_IsConversionDone()
bool ADC_IsConversionDone (void)
@Summary Returns true when the conversion is completed otherwise false.
@Description This routine is used to determine if conversion is completed. When conversion is complete routine returns true. It returns false otherwise.
@Preconditions ADC_Initialize() and ADC_StartConversion(void) function should have been called before calling this function.
@Returns true - If conversion is complete false - If conversion is not completed
@Param None
@Example uint16_t convertedValue;
ADC_Initialize(); ADC_StartConversion();
while(!ADC_IsConversionDone()); convertedValue = ADC_GetConversionResult();
Definition at line 105 of file adc.c.
{
    // Start the conversion
   return ((bool)(!ADCON0bits.GO_nDONE));
}
ADC_ISR()
void ADC_ISR (void)
@Summary Implements ISR
@Description This routine is used to implement the ISR for the interrupt-driven implementations.
@Returns None
@Param None
Definition at line 145 of file adc.c.
{
    // Clear the ADC interrupt flag
    PIR1bits.ADIF = 0;
    if(ADC_InterruptHandler)
    {
        ADC_InterruptHandler();
    }
}
References ADC_InterruptHandler.
Referenced by __interrupt().
ADC_SelectChannel()
void ADC_SelectChannel (adc_channel_t channel)
@Summary Allows selection of a channel for conversion
@Description This routine is used to select desired channel for conversion. available
@Preconditions ADC_Initialize() function should have been called before calling this function.
@Returns None
@Param Pass in required channel number "For available channel refer to enum under adc.h file"
@Example uint16_t convertedValue;
ADC_Initialize(); ADC_SelectChannel(AN1_Channel); ADC_StartConversion(); convertedValue = ADC_GetConversionResult();
Definition at line 90 of file adc.c.
{
    // select the A/D channel
    ADCON0bits.CHS = channel;
    // Turn on the ADC module
    ADCON0bits.ADON = 1;
}
ADC_SetInterruptHandler()
void ADC_SetInterruptHandler (void(*)(void) InterruptHandler)
@Summary Set Timer Interrupt Handler
@Description This sets the function to be called during the ISR
@Preconditions Initialize the ADC module with interrupt before calling this.
@Param Address of function to be set
@Returns None
Definition at line 156 of file adc.c.
{
    ADC_InterruptHandler = InterruptHandler;
}
References ADC_InterruptHandler.
Referenced by ADC_Initialize().
ADC_StartConversion()
void ADC_StartConversion (void)
@Summary Starts conversion
@Description This routine is used to start conversion of desired channel.
@Preconditions ADC_Initialize() function should have been called before calling this function.
@Returns None
@Param None
@Example uint16_t convertedValue;
ADC_Initialize();
ADC_StartConversion(); convertedValue = ADC_GetConversionResult();
Definition at line 98 of file adc.c.
{
    // Start the conversion
    ADCON0bits.GO_nDONE = 1;
}
ADC_TemperatureAcquisitionDelay()
void ADC_TemperatureAcquisitionDelay (void)
@Summary Acquisition Delay for temperature sensor
@Description This routine should be called when temperature sensor is used.
@Preconditions ADC_Initialize() function should have been called before calling this function.
@Returns None
@Param None
@Example uint16_t convertedValue;
ADC_Initialize();
ADC_StartConversion(); ADC_temperatureAcquisitionDelay(); convertedValue = ADC_GetConversionResult();
Definition at line 140 of file adc.c.
{
    __delay_us(200);
}
Variable Definitions
ADC_InterruptHandler
void(* ADC_InterruptHandler) (void) (void) extern
@Summary Timer Interrupt Handler
@Description This is a function pointer to the function that will be called during the ISR
@Preconditions Initialize the ADC module with interrupt before calling this isr.
@Param None
@Returns None
Definition at line 61 of file adc.c.
Referenced by ADC_ISR(), and ADC_SetInterruptHandler().