ATU100_PIC16F1938: mcc_generated_files/ext_int.h File Reference
ext_int.h File Reference
#include <xc.h>
Definitions and Macros
#define EXT_INT_InterruptFlagClear() (INTCONbits.INTF = 0)
#define EXT_INT_InterruptDisable() (INTCONbits.INTE = 0)
#define EXT_INT_InterruptEnable() (INTCONbits.INTE = 1)
#define EXT_INT_risingEdgeSet() (OPTION_REGbits.INTEDG = 1)
#define EXT_INT_fallingEdgeSet() (OPTION_REGbits.INTEDG = 0)
Function Declarations
void EXT_INT_Initialize (void)
void INT_ISR (void)
void INT_CallBack (void)
void INT_SetInterruptHandler (void(*InterruptHandler)(void))
void INT_DefaultInterruptHandler (void)
Variable Declarations
void(* INT_InterruptHandler)(void)
Definitions and Macros
EXT_INT_fallingEdgeSet
#define EXT_INT_fallingEdgeSet () (OPTION_REGbits.INTEDG = 0)
@Summary Sets the edge detect of the external interrupt to positive edge.
@Description This routine set the edge detect of the extern interrupt to positive edge.
After this routine is called the interrupt flag will be set when the external interrupt pins level transitions from a low to high level.
@Preconditions None.
@Returns None.
@Param None.
@Example Setting the external interrupt to handle positive edge interrupts set the edge EXT_INT_fallingEdgeSet(); clear the interrupt flag and enable the interrupt EXT_INT_InterruptFlagClear(); EXT_INT_InterruptEnable();
Definition at line 219 of file ext_int.h.
EXT_INT_InterruptDisable
#define EXT_INT_InterruptDisable () (INTCONbits.INTE = 0)
@Summary Clears the interrupt enable for INT
@Description This routine clears the interrupt enable for the external interrupt, INT. After calling this routine, external interrupts on this pin will not be serviced by the interrupt handler, INT.
@Preconditions None.
@Returns None.
@Param None.
@Example Changing the external interrupt edge detect from negative to positive clear the interrupt enable EXT_INT_InterruptDisable(); change the edge EXT_INT_fallingEdgeSet(); clear the interrupt flag and re-enable the interrupt EXT_INT_InterruptFlagClear(); EXT_INT_InterruptEnable();
Definition at line 126 of file ext_int.h.
EXT_INT_InterruptEnable
#define EXT_INT_InterruptEnable () (INTCONbits.INTE = 1)
@Summary Sets the interrupt enable for INT
@Description This routine sets the interrupt enable for the external interrupt, INT. After calling this routine, external interrupts on this pin will be serviced by the interrupt handler, INT.
@Preconditions None.
@Returns None.
@Param None.
@Example Setting the external interrupt to handle positive edge interrupts set the edge EXT_INT_fallingEdgeSet(); clear the interrupt flag and enable the interrupt EXT_INT_InterruptFlagClear(); EXT_INT_InterruptEnable();
Definition at line 157 of file ext_int.h.
EXT_INT_InterruptFlagClear
#define EXT_INT_InterruptFlagClear () (INTCONbits.INTF = 0)
EXT_INT Generated Driver File
@Company Microchip Technology Inc.
@File Name ext_int.c
@Summary This is the generated driver implementation file for the EXT_INT driver using PIC10 / PIC12 / PIC16 / PIC18 MCUs
@Description This source file provides implementations for driver APIs for EXT_INT. Generation Information : Product Revision : PIC10 / PIC12 / PIC16 / PIC18 MCUs - 1.81.7 Device : PIC16F1938 Driver Version : 1.11 The generated drivers are tested against the following: Compiler : XC8 2.31 and above MPLAB : MPLAB X 5.45 Section: Includes Section: Macros @Summary Clears the interrupt flag for INT
@Description This routine clears the interrupt flag for the external interrupt, INT.
@Preconditions None.
@Returns None.
@Param None.
@Example void INT_ISR(void) { User Area Begin->code
User Area End->code EXT_INT_InterruptFlagClear(); }
Definition at line 93 of file ext_int.h.
EXT_INT_risingEdgeSet
#define EXT_INT_risingEdgeSet () (OPTION_REGbits.INTEDG = 1)
@Summary Sets the edge detect of the external interrupt to negative edge.
@Description This routine set the edge detect of the extern interrupt to negative edge.
After this routine is called the interrupt flag will be set when the external interrupt pins level transitions from a high to low level.
@Preconditions None.
@Returns None.
@Param None.
@Example Setting the external interrupt to handle negative edge interrupts set the edge EXT_INT_fallingEdgeSet(); clear the interrupt flag and enable the interrupt EXT_INT_InterruptFlagClear(); EXT_INT_InterruptEnable();
Definition at line 188 of file ext_int.h.
Function Definitions
EXT_INT_Initialize()
void EXT_INT_Initialize (void)
Section: External Interrupt Initializers @Summary Initializes the external interrupt pins
@Description This routine initializes the EXT_INT driver to detect the configured edge, clear the interrupt flag and enable the interrupt.
The following external interrupts will be initialized: INT - EXT_INT
@Preconditions None.
@Returns None.
@Param None.
@Example Initialize the external interrupt pins EXT_INT_Initialize();
Definition at line 59 of file ext_int.c.
{
    // Clear the interrupt flag
    // Set the external interrupt edge detect
    EXT_INT_InterruptFlagClear();
    EXT_INT_fallingEdgeSet();
    // Set Default Interrupt Handler
    INT_SetInterruptHandler(INT_DefaultInterruptHandler);
    EXT_INT_InterruptEnable();
}
References EXT_INT_fallingEdgeSet, EXT_INT_InterruptEnable, EXT_INT_InterruptFlagClear, INT_DefaultInterruptHandler(), and INT_SetInterruptHandler().
Referenced by SYSTEM_Initialize().
INT_CallBack()
void INT_CallBack (void)
@Summary Callback function for EXT_INT - INT
@Description Allows for a specific callback function to be called in the INT ISR. It also allows for a non-specific interrupt handler to be called at runtime.
@Preconditions EXT_INT intializer called
@Returns None.
@Param None.
@Example EXT_INT_Initializer(); void INT_CallBack();
Definition at line 41 of file ext_int.c.
{
    // Add your custom callback code here
    if(INT_InterruptHandler)
    {
        INT_InterruptHandler();
    }
}
References INT_InterruptHandler.
Referenced by INT_ISR().
INT_DefaultInterruptHandler()
void INT_DefaultInterruptHandler (void)
@Summary Default Interrupt Handler for EXT_INT - INT pin
@Description This is a predefined interrupt handler to be used together with the INT_SetInterruptHandler() method. This handler is called every time the INT ISR is executed.
@Preconditions EXT_INT intializer called
@Returns None.
@Param None.
@Example EXT_INT_Initializer(); INT_SetInterruptHandler(INT_DefaultInterruptHandler);
Definition at line 54 of file ext_int.c.
{
    // add your INT interrupt custom code
    // or set custom function using INT_SetInterruptHandler()
}
Referenced by EXT_INT_Initialize().
INT_ISR()
void INT_ISR (void)
Section: External Interrupt Handlers @Summary Interrupt Service Routine for EXT_INT - INT pin
@Description This ISR will execute whenever the signal on the INT pin will transition to the preconfigured state.
@Preconditions EXT_INT intializer called
@Returns None.
@Param None.
Definition at line 32 of file ext_int.c.
{
    EXT_INT_InterruptFlagClear();
    // Callback function gets called everytime this ISR executes
    INT_CallBack();
}
References EXT_INT_InterruptFlagClear, and INT_CallBack().
Referenced by __interrupt().
INT_SetInterruptHandler()
void INT_SetInterruptHandler (void(*)(void) InterruptHandler)
@Summary Interrupt Handler Setter for EXT_INT - INT pin
@Description Allows selecting an interrupt handler for EXT_INT - INT at application runtime
@Preconditions EXT_INT intializer called
@Returns None.
@Param InterruptHandler function pointer.
@Example EXT_INT_Initializer(); INT_SetInterruptHandler(MyInterruptHandler);
Definition at line 50 of file ext_int.c.
{
    INT_InterruptHandler = InterruptHandler;
}
References INT_InterruptHandler.
Referenced by EXT_INT_Initialize().
Variable Definitions
INT_InterruptHandler
void(* INT_InterruptHandler) (void) (void) extern
@Summary Dynamic Interrupt Handler for EXT_INT - INT pin
@Description This is the dynamic interrupt handler to be used together with the INT_SetInterruptHandler() method. This handler is called every time the INT ISR is executed and allows any function to be registered at runtime.
@Preconditions EXT_INT intializer called
@Returns None.
@Param None.
@Example EXT_INT_Initializer(); INT_SetInterruptHandler(INT_InterruptHandler);
EXT_INT Generated Driver File
@Company Microchip Technology Inc.
@File Name ext_int.c
@Summary This is the generated driver implementation file for the EXT_INT driver using PIC10 / PIC12 / PIC16 / PIC18 MCUs
@Description This source file provides implementations for driver APIs for EXT_INT. Generation Information : Product Revision : PIC10 / PIC12 / PIC16 / PIC18 MCUs - 1.81.7 Device : PIC16F1938 Driver Version : 1.11 The generated drivers are tested against the following: Compiler : XC8 2.31 and above MPLAB : MPLAB X 5.45 Section: Includes
Definition at line 30 of file ext_int.c.
Referenced by INT_CallBack(), and INT_SetInterruptHandler().