ATU100_PIC16F1938: mcc_generated_files/interrupt_manager.c File Reference
interrupt_manager.c File Reference
#include "interrupt_manager.h"
#include "mcc.h"
Function Declarations
void __interrupt () INTERRUPT_InterruptManager(void)
Function Definitions
__interrupt()
void __interrupt ()
Generated Interrupt Manager Source File
@Company: Microchip Technology Inc.
@File Name: interrupt_manager.c
@Summary: This is the Interrupt Manager file generated using PIC10 / PIC12 / PIC16 / PIC18 MCUs
@Description: This header file provides implementations for global interrupt handling. For individual peripheral handlers please see the peripheral driver for all modules selected in the GUI. Generation Information : Product Revision : PIC10 / PIC12 / PIC16 / PIC18 MCUs - 1.81.7 Device : PIC16F1938 Driver Version : 2.04 The generated drivers are tested against the following: Compiler : XC8 2.31 and above or later MPLAB : MPLAB X 5.45
Definition at line 52 of file interrupt_manager.c.
{
    // interrupt handler
    if(INTCONbits.INTE == 1 && INTCONbits.INTF == 1)
    {
        INT_ISR();
    }
    else if(INTCONbits.IOCIE == 1 && INTCONbits.IOCIF == 1)
    {
        PIN_MANAGER_IOC();
    }
    else if(INTCONbits.PEIE == 1)
    {
        if(PIE1bits.ADIE == 1 && PIR1bits.ADIF == 1)
        {
            ADC_ISR();
        }
        else
        {
            //Unhandled Interrupt
        }
    }
    else
    {
        //Unhandled Interrupt
    }
}
References ADC_ISR(), INT_ISR(), and PIN_MANAGER_IOC().