ATU-100 EXT Firmware for PIC16F1938: include/main_main.h File Reference
main_main.h File Reference
Functions
void btn_push (void)
void lcd_prep (void)
void lcd_prep_short (void)
void lcd_swr (int, int)
void lcd_pwr (void)
void lcd_ind (void)
void crypto (void)
void show_reset (void)
void cells_init (void)
void test_init (void)
void button_proc (void)
void button_proc_test (void)
void atu_reset (void)
int get_reverse (void)
int get_forward (void)
int correction (int)
int get_swr (void)
void get_pwr (void)
void set_sw (char)
void coarse_cap ()
void sharp_cap ()
void sharp_ind ()
void coarse_tune ()
void tune (void)
void set_ind (char Ind)
void set_cap (char Cap)
Variables
static char ind = 0
static char cap = 0
static char SW = 0
static char step_cap = 0
static char step_ind = 0
static char L_linear = 0
static char C_linear = 0
static char L_q = 7
static char C_q = 7
static char D_correction = 1
static int Rel_Del
static int min_for_start
static int max_for_start
static int max_swr
int SWR
int PWR
char rready = 0
Function Documentation
atu_reset()
void atu_reset (void)
Definition at line 165 of file main_main.h.
References cap, ind, Rel_Del, set_cap(), and set_ind().
Referenced by tune().
                  {
    ind = 0;
    cap = 0;
    set_ind(ind);
    set_cap(cap);
    Vdelay_ms(Rel_Del);
 }
btn_push()
void btn_push (void)
Definition at line 508 of file main.c.
References bit_byte_t::byte, lcd_ind(), lcd_pwr(), led_wr_str(), Loss_ind, Loss_mode, n_Tx, p_Tx, Power_old, SW, SWR, swr_a, SWR_fixed_old, SWR_old, tune(), and type.
Referenced by button_proc().
                 {
     asm("CLRWDT");
     if ((type == 4) || (type == 5)) { // 128*64 OLED
         led_wr_str(2, 16 + 12 * 4, "TUNE", 4);
     } else if (type != 0) { // 1602 LCD & 128*32 OLED
         led_wr_str(1, 4, "TUNE", 4);
     } else {
         LATBbits.LATB6 = 1;
         LATBbits.LATB7 = 1;
     }
     tune();
     if (type == 0) { // real-time 2-colors led work
         if (swr <= 150) {
             LATBbits.LATB6 = 0;
             LATBbits.LATB7 = 1;
         }// Green
         else if (swr <= 250) {
             PORTBbits.RB6 = 0;
             PORTBbits.RB7 = 0;
         }// Orange
         else {
             PORTBbits.RB6 = 1;
             PORTBbits.RB7 = 0;
         } // Red
     } else if ((Loss_mode == 0) || (Loss_ind == 0)) {
         lcd_ind();
     }
     EEPROM_Write(255, cap.byte);
     EEPROM_Write(254, ind.byte);
     EEPROM_Write(253, SW);
     EEPROM_Write(252, swr_a / 256);
     EEPROM_Write(251, swr_a % 256);
     SWR_old = 10000;
     Power_old = 10000;
     lcd_pwr();
     SWR_fixed_old = SWR;
     p_Tx = 0;
     n_Tx = 1;
     asm("CLRWDT");
     return;
 }
button_proc()
void button_proc (void)
Definition at line 326 of file main.c.
References Auto, Auto_mem, btn_push(), bypas, bit_byte_t::byte, cap_mem, dysp, dysp_cnt, dysp_cnt_mult, Dysp_delay, dysp_on(), EEPROM_AUTO_MODE, ind_mem, L_invert, lcd_ind(), lcd_pwr(), led_wr_str(), Loss_mode, n_Tx, p_Tx, Relay_off, set_cap(), set_ind(), show_reset(), Soft_tune, SW, SW_mem, tune_btn_release, and type.
Referenced by main().
{
     if ((tune_btn_release == 0) && Button(&PORTB, 0, 50, 1)) {
         tune_btn_release = 1;
     }
     if ((tune_btn_release == 0) && Button(&PORTB, 0, 50, 0)) {
         dysp_cnt = Dysp_delay * dysp_cnt_mult;
     }
     if ((Button(&PORTB, 0, 50, 0) && tune_btn_release) || Soft_tune) {
         if (dysp == 0) { // dysplay ON
             if (Relay_off == 1) {
                 set_ind(ind.byte);
                 set_cap(cap.byte);
                 set_SW(SW);
             }
             dysp = 1;
             dysp_on();
             dysp_cnt = Dysp_delay * dysp_cnt_mult;
             return;
         }
         dysp_cnt = Dysp_delay * dysp_cnt_mult;
         Delay_ms(250);
         asm("CLRWDT");
         if (Soft_tune == 0 & PORTBbits.RB0 == 1) { // short press button
             show_reset();
             bypas = 0;
         } else { // long press button
             p_Tx = 1; //
             n_Tx = 0; // TX request
             Delay_ms(250); //
             btn_push();
             bypas = 0;
             Soft_tune = 0;
             tune_btn_release = 0;
         }
     }
     if (Button(&PORTB, 2, 50, 0)) { // BYP button
         if (dysp == 0) { // dysplay ON
             if (Relay_off == 1) {
                 set_ind(ind.byte);
                 set_cap(cap.byte);
                 set_SW(SW);
             }
             dysp = 1;
             dysp_on();
             dysp_cnt = Dysp_delay * dysp_cnt_mult;
             return;
         }
         dysp_cnt = Dysp_delay * dysp_cnt_mult;
         asm("CLRWDT");
         if (bypas == 0) {
             bypas = 1;
             cap_mem = cap.byte;
             ind_mem = ind.byte;
             SW_mem = SW;
             cap.byte = 0;
             if (L_invert) {
                 ind.byte = 255;
             } else {
                 ind.byte = 0;
             }
             SW = 1;
             set_ind(ind.byte);
             set_cap(cap.byte);
             set_SW(SW);
             if (Loss_mode == 0) {
                 lcd_ind();
             }
             Auto_mem = Auto;
             Auto = 0;
         } else {
             bypas = 0;
             cap.byte = cap_mem;
             ind.byte = ind_mem;
             SW = SW_mem;
             set_cap(cap.byte);
             set_ind(ind.byte);
             set_SW(SW);
             if (Loss_mode == 0) {
                 lcd_ind();
             }
             Auto = Auto_mem;
         }
         if ((type == 4) || (type == 5)) { // 128*64 OLED
             if (Auto && !bypas) led_wr_str(0, 16 + 8 * 12, ".", 1);
             else if (!Auto && bypas) led_wr_str(0, 16 + 8 * 12, "_", 1);
             else led_wr_str(0, 16 + 8 * 12, " ", 1);
         } else if (type != 0) { //  1602 LCD  or 128*32 OLED
             if (Auto && !bypas) led_wr_str(0, 8, ".", 1);
             else if (!Auto && bypas) led_wr_str(0, 8, "_", 1);
             else led_wr_str(0, 8, " ", 1);
         }
         asm("CLRWDT");
         while (Button(&PORTB, 2, 50, 0)) {
             lcd_pwr();
             asm("CLRWDT");
         }
     }
     if (Button(&PORTB, 1, 50, 0) && (bypas == 0)) { // Auto button
         if (dysp == 0) { // dysplay ON
             if (Relay_off == 1) {
                 set_ind(ind.byte);
                 set_cap(cap.byte);
                 set_SW(SW);
             }
             dysp = 1;
             dysp_on();
             dysp_cnt = Dysp_delay * dysp_cnt_mult;
             return;
         }
         dysp_cnt = Dysp_delay * dysp_cnt_mult;
         asm("CLRWDT");
         if (Auto == 0) {
             Auto = 1;
         } else {
             Auto = 0;
         }
         EEPROM_Write(EEPROM_AUTO_MODE, Auto);
         if ((type == 4) || (type == 5)) { // 128*64 OLED
             if (Auto & !bypas) led_wr_str(0, 16 + 8 * 12, ".", 1);
             else if (!Auto && bypas) led_wr_str(0, 16 + 8 * 12, "_", 1);
             else led_wr_str(0, 16 + 8 * 12, " ", 1);
         } else if (type != 0) { //  1602 LCD  or 128*32 OLED
             if (Auto && !bypas) led_wr_str(0, 8, ".", 1);
             else if (!Auto && bypas) led_wr_str(0, 8, "_", 1);
             else led_wr_str(0, 8, " ", 1);
         }
         asm("CLRWDT");
         while (Button(&PORTB, 1, 50, 0)) {
             lcd_pwr();
             asm("CLRWDT");
         }
     }
     return;
 }
button_proc_test()
void button_proc_test (void)
Definition at line 256 of file main.c.
References bypas, bit_byte_t::byte, L, L_mult, lcd_ind(), lcd_pwr(), led_wr_str(), set_cap(), set_ind(), set_sw(), SW, and type.
Referenced by main().
{
     if (Button(&PORTB, 0, 50, 0)) { // Tune btn
         Delay_ms(250);
         asm("CLRWDT");
         if (PORTBbits.RB0 == 1) { // short press button
             if (SW == 0) SW = 1;
             else SW = 0;
             set_sw(SW);
             lcd_ind();
         } else { // long press button
             if (L == 1) L = 0;
             else L = 1;
             if (L == 1) {
                 if (type == 4 || type == 5) // 128*64 OLED
                     led_wr_str(0, 16 + 12 * 8, "l", 1);
                 else if (type != 0) // 1602 LCD & 128*32 OLED
                     led_wr_str(0, 8, "l", 1);
             } else {
                 if (type == 4 || type == 5) // 128*64 OLED
                     led_wr_str(0, 16 + 12 * 8, "c", 1);
                 else if (type != 0) // 1602 LCD & 128*32 OLED
                     led_wr_str(0, 8, "c", 1);
             }
         }
         while (Button(&PORTB, 0, 50, 0)) {
             lcd_pwr();
             asm("CLRWDT");
         }
     } // END Tune btn
     if (Button(&PORTB, 2, 50, 0)) { // BYP button
         asm("CLRWDT");
         while (PORTBbits.RB2 == 0) {
             if (L && ind.byte < 32 * L_mult - 1) {
                 ind.byte++;
                 set_ind(ind.byte);
             } else if (!L && cap.byte < 32 * L_mult - 1) {
                 cap.byte++;
                 set_cap(cap.byte);
             }
             lcd_ind();
             lcd_pwr();
             Delay_ms(30);
             asm("CLRWDT");
         }
     } // end of BYP button
     if (Button(&PORTB, 1, 50, 0) && (bypas == 0)) { // Auto button
         asm("CLRWDT");
         while (PORTBbits.RB1 == 0) {
             if (L && ind.byte > 0) {
                 ind.byte--;
                 set_ind(ind.byte);
             } else if (!L && cap.byte > 0) {
                 cap.byte--;
                 set_cap(cap.byte);
             }
             lcd_ind();
             lcd_pwr();
             Delay_ms(30);
             asm("CLRWDT");
         }
     }
     return;
 }
cells_init()
void cells_init (void)
Definition at line 1083 of file main.c.
References Auto, Auto_delta, C_linear, C_q, Cap1, Cap2, Cap3, Cap4, Cap5, Cap6, Cap7, D_correction, Dysp_delay, EEPROM_AUTO_DELTA, EEPROM_AUTO_MODE, EEPROM_DISP_TYPE, EEPROM_OLED_ADDR, EEPROM_PMAX_FOR_START, EEPROM_PMIN_FOR_START, EEPROM_RELAY_DELAY, Fid_loss, Ind1, Ind2, Ind3, Ind4, Ind5, Ind6, Ind7, K_Mult, L_invert, L_linear, L_q, Loss_ind, max_for_start, max_swr, min_for_start, P_High, Rel_Del, Relay_off, and type.
Referenced by main().
                       {
     asm("CLRWDT");
 #if defined(READ_OLED_ADDR_FROM_EEPROM)
     oled_addr = EEPROM_Read(EEPROM_OLED_ADDR);                              // OLED I2C address
 #endif
     type = EEPROM_Read(EEPROM_DISP_TYPE);                                   // type of display
     if (EEPROM_Read(EEPROM_AUTO_MODE) == 1) {                               /* Check if AUTO mode should be enabled */
         Auto = 1;
     }
     Rel_Del = Bcd2Dec(EEPROM_Read(EEPROM_RELAY_DELAY));                     // Relay's Delay
     Auto_delta = Bcd2Dec(EEPROM_Read(EEPROM_AUTO_DELTA)) * 10;              // Auto_delta
     min_for_start = Bcd2Dec(EEPROM_Read(EEPROM_PMIN_FOR_START)) * 10;       // P_min_for_start
     max_for_start = Bcd2Dec(EEPROM_Read(EEPROM_PMAX_FOR_START)) * 10;       // P_max_for_start
     // 7  - shift down
     // 8 - shift left
     max_swr = Bcd2Dec(EEPROM_Read(9)) * 10;                                 /* Max SWR */
     L_q = EEPROM_Read(10);
     L_linear = EEPROM_Read(11);
     C_q = EEPROM_Read(12);
     C_linear = EEPROM_Read(13);
     D_correction = EEPROM_Read(14);
     L_invert = EEPROM_Read(15);
     asm("CLRWDT");
     Ind1 = Bcd2Dec(EEPROM_Read(16)) * 100 + Bcd2Dec(EEPROM_Read(17));       /* Ind1 */
     Ind2 = Bcd2Dec(EEPROM_Read(18)) * 100 + Bcd2Dec(EEPROM_Read(19));       /* Ind2 */
     Ind3 = Bcd2Dec(EEPROM_Read(20)) * 100 + Bcd2Dec(EEPROM_Read(21));       /* Ind3 */
     Ind4 = Bcd2Dec(EEPROM_Read(22)) * 100 + Bcd2Dec(EEPROM_Read(23));       /* Ind4 */
     Ind5 = Bcd2Dec(EEPROM_Read(24)) * 100 + Bcd2Dec(EEPROM_Read(25));       /* Ind5 */
     Ind6 = Bcd2Dec(EEPROM_Read(26)) * 100 + Bcd2Dec(EEPROM_Read(27));       /* Ind6 */
     Ind7 = Bcd2Dec(EEPROM_Read(28)) * 100 + Bcd2Dec(EEPROM_Read(29));       /* Ind7 */
     Cap1 = Bcd2Dec(EEPROM_Read(32)) * 100 + Bcd2Dec(EEPROM_Read(33));       /* Cap1 */
     Cap2 = Bcd2Dec(EEPROM_Read(34)) * 100 + Bcd2Dec(EEPROM_Read(35));       /* Cap2 */
     Cap3 = Bcd2Dec(EEPROM_Read(36)) * 100 + Bcd2Dec(EEPROM_Read(37));       /* Cap3 */
     Cap4 = Bcd2Dec(EEPROM_Read(38)) * 100 + Bcd2Dec(EEPROM_Read(39));       /* Cap4 */
     Cap5 = Bcd2Dec(EEPROM_Read(40)) * 100 + Bcd2Dec(EEPROM_Read(41));       /* Cap5 */
     Cap6 = Bcd2Dec(EEPROM_Read(42)) * 100 + Bcd2Dec(EEPROM_Read(43));       /* Cap6 */
     Cap7 = Bcd2Dec(EEPROM_Read(44)) * 100 + Bcd2Dec(EEPROM_Read(45));       /* Cap7 */
     P_High = EEPROM_Read(0x30);                                             /* High power mode */
     K_Mult = Bcd2Dec(EEPROM_Read(0x31));                                    /* Tandem Match ratio */
     Dysp_delay = Bcd2Dec(EEPROM_Read(0x32));                                /* Display ON delay */
     Loss_ind = EEPROM_Read(0x33);
     Fid_loss = Bcd2Dec(EEPROM_Read(0x34));
     Relay_off = Bcd2Dec(EEPROM_Read(0x35));
     asm("CLRWDT");
     return;
 }
coarse_cap()
void coarse_cap ()
Definition at line 270 of file main_main.h.
References cap, get_swr(), set_cap(), step_cap, and SWR.
Referenced by coarse_tune().
                   {
    char step = 2;
    char count;
    int min_swr;
    cap = 0;
    set_cap(cap);
    SWR = get_swr();
    min_swr = SWR + SWR/20;
    for(count=step; count<=127; count+=step) {
       set_cap(count);
       SWR = get_swr();
       if(SWR<min_swr) {
          min_swr = SWR + SWR/20;
          cap = count;
          step_cap = step;
          //if((min_swr-SWR)<100 & SWR>300) step = 5; else step = 3;
          if(count>=30) step = count/10;
          if(SWR<120) break;
       }
       else break;
    }
    set_cap(cap);
    return;
 }
coarse_tune()
void coarse_tune ()
Definition at line 296 of file main_main.h.
References cap, coarse_cap(), get_swr(), ind, set_cap(), set_ind(), step_cap, step_ind, and SWR.
Referenced by tune().
                    {
    char step = 4;
    char count;
    char mem_cap, mem_step_cap;
    int min_swr;
    mem_cap = 0;
    step_ind = step;
    mem_step_cap = 2;
    min_swr = SWR + SWR/20;
    for(count=step; count<=127; count+=step) {
       set_ind(count);
       coarse_cap();
       SWR = get_swr();
       if(SWR<min_swr) {
          min_swr = SWR + SWR/20;
          ind = count;
          mem_cap = cap;
          step_ind = step;
          mem_step_cap = step_cap;
          if(count>=50) step = count/10;
          if(SWR<120) break;
       }
       else break;     // ?? Brute Force (no)
    }
    cap = mem_cap;
    set_ind(ind);
    set_cap(cap);
    step_cap = mem_step_cap;
    Delay_ms(10);
    return;
 }
correction()
int correction (int input)
Definition at line 38 of file main_main.h.
Referenced by get_pwr().
{
      input *= 3; // Devider compensation
      if(input <= 80) return 0;
      if(input <= 171) input += 244;
      else if(input <= 328) input += 254;
      else if(input <= 582) input += 280;
      else if(input <= 820) input += 297;
      else if(input <= 1100) input += 310;
      else if(input <= 2181) input += 430;
      else if(input <= 3322) input += 484;
      else if(input <= 4623) input += 530;
      else if(input <= 5862) input += 648;
      else if(input <= 7146) input += 743;
      else if(input <= 8502) input += 800;
      else if(input <= 10500) input += 820;
      else  input += 850;
      //
      return input;
 }
crypto()
void crypto (void)
get_forward()
int get_forward (void)
Definition at line 79 of file main_main.h.
References Forward.
Referenced by get_pwr().
                   {
    int Forward;
    FVRCON = 0b10000001; // ADC 1024 vmV Vref
    while(FVRCON.B6 == 0);
    Forward = ADC_Get_Sample(1);
    if(Forward <= 1000) return Forward;
    FVRCON = 0b10000010; // ADC 2048 vmV Vref
    while(FVRCON.B6 == 0);
    Forward = ADC_Get_Sample(1);
    if(Forward <= 1000) return Forward * 2;
    FVRCON = 0b10000011; // ADC 4096 vmV Vref
    while(FVRCON.B6 == 0);
    Forward = ADC_Get_Sample(1);
    return Forward * 4;
 }
get_pwr()
void get_pwr (void)
Definition at line 95 of file main_main.h.
References correction(), D_correction, Forward, get_forward(), get_reverse(), PWR, and SWR.
Referenced by get_swr().
                {
    long Forward, Reverse;
    float p;
    asm CLRWDT;
    //
    Forward = get_forward();
    Reverse = get_reverse();
    if(D_correction==1) p = correction(Forward);
    else p = Forward;
    //
    if(Reverse >= Forward)
       Forward = 999;
    else {
       Forward = ((Forward + Reverse) * 100) / (Forward - Reverse);
       if(Forward>999) Forward = 999;
    }
    //
    p = p * 10 / 1000;   // mV to Volts
    p = p / 1.414;
    p = p * p / 5;
    p = p + 0.5;    // rounding to 0.1 W
    PWR = p;   // 0 - 1510 (151.0 Watts)
    SWR = Forward;
 }
get_reverse()
int get_reverse (void)
Definition at line 62 of file main_main.h.
Referenced by get_pwr().
                   {
    int Reverse;
    FVRCON = 0b10000001; // ADC 1024 vmV Vref
    while(FVRCON.B6 == 0);
    Reverse = ADC_Get_Sample(0);
    if(Reverse <= 1000) return Reverse;
    FVRCON = 0b10000010; // ADC 2048 vmV Vref
    while(FVRCON.B6 == 0);
    Reverse = ADC_Get_Sample(0);
    if(Reverse <= 1000) return Reverse * 2;
    FVRCON = 0b10000011; // ADC 4096 vmV Vref
    while(FVRCON.B6 == 0);
    Reverse = ADC_Get_Sample(0);
    return Reverse * 4;
 }
get_swr()
int get_swr (void)
Definition at line 120 of file main_main.h.
References get_pwr(), max_for_start, min_for_start, PWR, rready, show_reset(), and SWR.
Referenced by coarse_cap(), coarse_tune(), sharp_cap(), sharp_ind(), and tune().
               {
    get_pwr();
    while((PWR<=min_for_start | (PWR> max_for_start & max_for_start>0))) {  // waiting for good power
       asm CLRWDT;
       get_pwr();
       if(Button(&PORTB, 0, 5, 1)) rready = 1;
       if(rready==1 & Button(&PORTB, 0, 5, 0)) { //  press button  Tune
          show_reset();
          SWR = 0;
          return SWR;
       }
    } //  good power
    return SWR;
 }
lcd_ind()
void lcd_ind (void)
Definition at line 952 of file main.c.
References Cap1, Cap2, Cap3, Cap4, Cap5, Cap6, Cap7, Ind1, Ind2, Ind3, Ind4, Ind5, Ind6, Ind7, led_wr_str(), SW, type, work_int, work_str, and work_str_2.
Referenced by btn_push(), button_proc(), button_proc_test(), lcd_prep(), main(), show_pwr(), and show_reset().
                {
     char column;
     asm("CLRWDT");
     if (1) {
         work_int = 0;
         if (ind.B0) work_int += Ind1;
         if (ind.B1) work_int += Ind2;
         if (ind.B2) work_int += Ind3;
         if (ind.B3) work_int += Ind4;
         if (ind.B4) work_int += Ind5;
         if (ind.B5) work_int += Ind6;
         if (ind.B6) work_int += Ind7;
         if (work_int > 9999) { // more then 9999 nH
             work_int += 50; // round
             IntToStr(work_int, work_str);
             work_str_2[0] = work_str[1];
             work_str_2[1] = work_str[2];
             work_str_2[2] = '.';
             work_str_2[3] = work_str[3];
         } else {
             IntToStr(work_int, work_str);
             if (work_str[2] != ' ') work_str_2[0] = work_str[2];
             else work_str_2[0] = '0';
             work_str_2[1] = '.';
             if (work_str[3] != ' ') work_str_2[2] = work_str[3];
             else work_str_2[2] = '0';
             if (work_str[4] != ' ') work_str_2[3] = work_str[4];
             else work_str_2[3] = '0';
         }
         if (type == 4 | type == 5) { // 128*64 OLED
             if (SW == 1) column = 4;
             else column = 6;
             led_wr_str(column, 16, "L=", 2);
             led_wr_str(column, 16 + 6 * 12, "uH", 2);
             led_wr_str(column, 16 + 2 * 12, work_str_2, 4);
         } else if (type == 2 | type == 3) {// 128*32 OLED
             if (SW == 1) column = 0;
             else column = 1;
             led_wr_str(column, 9, "L=", 2);
             led_wr_str(column, 15, "uH", 2);
             led_wr_str(column, 11, work_str_2, 4);
         } else if (type == 1) { //  1602 LCD
             if (SW == 1) column = 0;
             else column = 1;
             led_wr_str(column, 9, "L=", 2);
             led_wr_str(column, 15, "u", 1);
             led_wr_str(column, 11, work_str_2, 4);
         }
     }
     asm("CLRWDT");
     if (1) {
         work_int = 0;
         if (cap.B0) work_int += Cap1;
         if (cap.B1) work_int += Cap2;
         if (cap.B2) work_int += Cap3;
         if (cap.B3) work_int += Cap4;
         if (cap.B4) work_int += Cap5;
         if (cap.B5) work_int += Cap6;
         if (cap.B6) work_int += Cap7;
         IntToStr(work_int, work_str);
         work_str_2[0] = work_str[2];
         work_str_2[1] = work_str[3];
         work_str_2[2] = work_str[4];
         work_str_2[3] = work_str[5];
         if (type == 4 | type == 5) { // 128*64 OLED
             if (SW == 1) column = 6;
             else column = 4;
             led_wr_str(column, 16, "C=", 2);
             led_wr_str(column, 16 + 6 * 12, "pF", 2);
             led_wr_str(column, 16 + 2 * 12, work_str_2, 4);
         } else if (type == 2 | type == 3) {// 128*32 OLED
             if (SW == 1) column = 1;
             else column = 0;
             led_wr_str(column, 9, "C=", 2);
             led_wr_str(column, 15, "pF", 2);
             led_wr_str(column, 11, work_str_2, 4);
         } else if (type == 1) { // 1602 LCD
             if (SW == 1) column = 1;
             else column = 0;
             led_wr_str(column, 9, "C=", 2);
             led_wr_str(column, 15, "p", 1);
             led_wr_str(column, 11, work_str_2, 4);
         }
     }
     asm("CLRWDT");
     return;
 }
lcd_prep()
void lcd_prep (void)
Definition at line 556 of file main.c.
References Auto, lcd_ind(), lcd_prep_short, led_wr_str(), P_High, and type.
Referenced by main(), and Test_init().
                 {
     asm("CLRWDT");
     if (type == 4 | type == 5) { // 128*64 OLED
         if (lcd_prep_short == 0) {
             led_wr_str(0, 22, "ATU-100", 7);
             led_wr_str(2, 6, "EXT board", 9);
             led_wr_str(4, 16, "by N7DDC", 8);
             led_wr_str(6, 4, "FW ver 3.2", 10);
             asm("CLRWDT");
             Delay_ms(600);
             asm("CLRWDT");
             Delay_ms(500);
             asm("CLRWDT");
             led_wr_str(0, 16, "        ", 8);
             led_wr_str(2, 4, "          ", 10);
             led_wr_str(4, 16, "        ", 8);
             led_wr_str(6, 4, "          ", 10);
         }
         Delay_ms(150);
         if (P_High == 1) led_wr_str(0, 16, "PWR=  0W", 8);
         else led_wr_str(0, 16, "PWR=0.0W", 8);
         led_wr_str(2, 16, "SWR=0.00", 8);
         if (Auto) led_wr_str(0, 16 + 8 * 12, ".", 1);
     } else if (type != 0) { // 1602 LCD & 128*32 OLED
         if (lcd_prep_short == 0) {
             led_wr_str(0, 4, "ATU-100", 7);
             led_wr_str(1, 3, "EXT board", 9);
             asm("CLRWDT");
             Delay_ms(700);
             asm("CLRWDT");
             Delay_ms(500);
             asm("CLRWDT");
             led_wr_str(0, 4, "by N7DDC", 8);
             led_wr_str(1, 3, "FW ver 3.2", 10);
             asm("CLRWDT");
             Delay_ms(600);
             asm("CLRWDT");
             Delay_ms(500);
             asm("CLRWDT");
             led_wr_str(0, 4, "        ", 8);
             led_wr_str(1, 3, "          ", 10);
         }
         Delay_ms(150);
         if (P_High == 1) led_wr_str(0, 0, "PWR=  0W", 8);
         else led_wr_str(0, 0, "PWR=0.0W", 8);
         led_wr_str(1, 0, "SWR=0.00", 8);
         if (Auto) led_wr_str(0, 8, ".", 1);
     }
     asm("CLRWDT");
     lcd_ind();
     return;
 }
lcd_prep_short()
void lcd_prep_short (void)
lcd_pwr()
void lcd_pwr (void)
Definition at line 823 of file main.c.
References Auto, Auto_delta, but, button_delay(), bit_byte_t::byte, dysp, dysp_cnt, dysp_cnt_mult, Dysp_delay, dysp_on(), get_pwr(), lcd_swr(), led_wr_str(), Overload, Power, PWR, Relay_off, set_cap(), set_ind(), show_pwr(), Soft_tune, SW, SWR, SWR_fixed_old, SWR_old, tune_btn_release, and type.
Referenced by btn_push(), button_proc(), button_proc_test(), main(), and show_reset().
                {
     int p = 0;
     char peak_cnt;
     int delta = Auto_delta - 100;
     char cnt;
     int SWR_fixed;
     PWR = 0;
     asm("CLRWDT");
     if (dysp == 0 & Relay_off == 1) {
         get_pwr();
         if (PWR >= 10) {
             set_ind(ind.byte);
             set_cap(cap.byte);
             set_SW(SW);
             dysp = 1;
             dysp_on(); // dysplay ON
             dysp_cnt = Dysp_delay * dysp_cnt_mult;
         }
         return;
     }
     // peak detector
     cnt = 120;
     for (peak_cnt = 0; peak_cnt < cnt; peak_cnt++) {
         if (PORTBbits.RB1 == 0 | PORTBbits.RB2 == 0 | (PORTBbits.RB0 == 0 & tune_btn_release)) {
             button_delay();
             if (but == 1) {
                 but = 0;
                 return;
             }
         }
         get_pwr();
         if (PWR > p) {
             p = PWR;
             SWR_fixed = SWR;
         }
         Delay_ms(3);
     }
     asm("CLRWDT");
     if (p >= 100) {
         p = (p + 5) / 10;
         p *= 10;
     } // round to 1 W if more then 100 W
     Power = p;
     if (Power < 10) SWR_fixed = 0;
     lcd_swr(SWR_fixed);
     if (Power >= 10 & Dysp_delay > 0) {
         dysp_cnt = Dysp_delay * dysp_cnt_mult;
     }
     if (Auto && SWR_fixed >= Auto_delta && ((SWR_fixed > SWR_fixed_old && (SWR_fixed - SWR_fixed_old) > delta) || (SWR_fixed < SWR_fixed_old && (SWR_fixed_old - SWR_fixed) > delta) || SWR_fixed_old == 999))
         Soft_tune = 1;
     if ((PORTBbits.RB1 == 0) || (PORTBbits.RB2 == 0) || ((PORTBbits.RB0 == 0) && tune_btn_release)) {
         button_delay();
         if (but == 1) {
             but = 0;
             return;
         }
     } // Fast return if button pressed
     show_pwr(Power, SWR_fixed);
     if (PORTBbits.RB1 == 0 || PORTBbits.RB2 == 0 || (PORTBbits.RB0 == 0 && tune_btn_release)) {
         button_delay();
         if (but == 1) {
             but = 0;
             return;
         }
     }
     asm("CLRWDT");
     if (Overload == 1) {
         if (type == 4 || type == 5) { // 128*64 OLED
             led_wr_str(2, 16, "        ", 8);
             delay_ms(100);
             led_wr_str(2, 16, "OVERLOAD", 8);
             delay_ms(500);
             asm("CLRWDT");
             led_wr_str(2, 16, "        ", 8);
             delay_ms(300);
             asm("CLRWDT");
             led_wr_str(2, 16, "OVERLOAD", 8);
             delay_ms(500);
             asm("CLRWDT");
             led_wr_str(2, 16, "        ", 8);
             delay_ms(300);
             asm("CLRWDT");
             led_wr_str(2, 16, "OVERLOAD", 8);
             delay_ms(500);
             asm("CLRWDT");
             led_wr_str(2, 16, "        ", 8);
             delay_ms(100);
             led_wr_str(2, 16, "SWR=    ", 8);
         } else if (type != 0) { // 1602  & 128*32
             led_wr_str(1, 0, "        ", 8);
             delay_ms(100);
             led_wr_str(1, 0, "OVERLOAD", 8);
             delay_ms(500);
             asm("CLRWDT");
             led_wr_str(1, 0, "        ", 8);
             delay_ms(300);
             asm("CLRWDT");
             led_wr_str(1, 0, "OVERLOAD", 8);
             delay_ms(500);
             asm("CLRWDT");
             led_wr_str(1, 0, "        ", 8);
             delay_ms(300);
             asm("CLRWDT");
             led_wr_str(1, 0, "OVERLOAD", 8);
             delay_ms(500);
             asm("CLRWDT");
             led_wr_str(1, 0, "        ", 8);
             delay_ms(100);
             led_wr_str(1, 0, "SWR=    ", 8);
         }
         asm("CLRWDT");
         SWR_old = 10000;
         lcd_swr(SWR_fixed);
     }
     return;
 }
lcd_swr()
void lcd_swr (int , int)
set_cap()
void set_cap (char Cap)
Definition at line 148 of file main_main.h.
References Cap_10, Cap_100, Cap_1000, Cap_22, Cap_220, Cap_47, Cap_470, and Rel_Del.
Referenced by atu_reset(), coarse_cap(), coarse_tune(), sharp_cap(), and tune().
                        { // 0 - 31
    Cap_10  =  Cap.B0;
    Cap_22  =  Cap.B1;
    Cap_47  =  Cap.B2;
    Cap_100 =  Cap.B3;
    Cap_220 =  Cap.B4;
    Cap_470 =  Cap.B5;
    Cap_1000 =  Cap.B6;
    //
    Vdelay_ms(Rel_Del);
 }
set_ind()
void set_ind (char Ind)
Definition at line 135 of file main_main.h.
References Ind_005, Ind_011, Ind_022, Ind_045, Ind_1, Ind_22, Ind_45, and Rel_Del.
Referenced by atu_reset(), coarse_tune(), sharp_ind(), and tune().
                        {  // 0 - 31
    //
    Ind_005 = Ind.B0;
    Ind_011 = Ind.B1;
    Ind_022 = Ind.B2;
    Ind_045 = Ind.B3;
    Ind_1   = Ind.B4;
    Ind_22  = Ind.B5;
    Ind_45  = Ind.B6;
    //
    Vdelay_ms(Rel_Del);
 }
set_sw()
void set_sw (char SW)
Definition at line 160 of file main_main.h.
References Cap_sw, Rel_Del, and SW.
Referenced by tune().
                      {  // 0 - IN,  1 - OUT
    Cap_sw = SW;
    Vdelay_ms(Rel_Del);
 }
sharp_cap()
void sharp_cap ()
Definition at line 331 of file main_main.h.
References C_q, cap, get_swr(), set_cap(), step_cap, and SWR.
Referenced by tune().
                  {
    char range, count, max_range, min_range, max_count = 1;
    int min_swr;
    range = step_cap;
    //
    for(count==C_q; count>0; count-- )max_count *= 2;
    max_count -= 1;
    max_range = cap + range;
    if(max_range>max_count) max_range = max_count;
    if(cap>range) min_range = cap - range; else min_range = 0;
    cap = min_range;
    set_cap(cap);
    SWR = get_swr();
    if(SWR==0) return;
    min_SWR = SWR;
    for(count=min_range+1; count<=max_range; count++)  {
       set_cap(count);
       SWR = get_swr();
       if(SWR==0) return;
       if(SWR>=min_SWR) { Delay_ms(10); SWR = get_swr(); }
       if(SWR>=min_SWR) { Delay_ms(10); SWR = get_swr(); }
       if(SWR < min_SWR) {
          min_SWR = SWR;
          cap = count;
          if(SWR<120) break;
       }
       else break;
    }
    set_cap(cap);
    return;
 }
sharp_ind()
void sharp_ind ()
Definition at line 363 of file main_main.h.
References get_swr(), ind, L_q, set_ind(), step_ind, and SWR.
Referenced by tune().
                  {
    char range, count, max_range, min_range, max_count = 1;
    int min_SWR;
    range = step_ind;
    //
    for(count==L_q; count>0; count--) max_count *= 2;
    max_count -= 1;
    max_range = ind + range;
    if(max_range>max_count) max_range = max_count;
    if(ind>range) min_range = ind - range; else min_range = 0;
    ind = min_range;
    set_ind(ind);
    SWR = get_swr();
    if(SWR==0) return;
    min_SWR = SWR;
    for(count=min_range+1; count<=max_range; count++) {
       set_ind(count);
       SWR = get_swr();
       if(SWR==0) return;
       if(SWR>=min_SWR) { Delay_ms(10); SWR = get_swr(); }
       if(SWR>=min_SWR) { Delay_ms(10); SWR = get_swr(); }
       if(SWR < min_SWR) {
          min_SWR = SWR;
          ind = count;
          if(SWR<120) break;
       }
       else break;
    }
    set_ind(ind);
    return;
 }
show_reset()
void show_reset (void)
Definition at line 470 of file main.c.
References atu_reset(), lcd_ind(), lcd_pwr(), led_wr_str(), Loss_mode, n_Tx, p_Tx, Power_old, PWR, set_sw(), SW, SWR, SWR_fixed_old, SWR_old, and type.
Referenced by button_proc(), and get_swr().
                   {
     atu_reset();
     SW = 1;
     set_sw(SW);
     EEPROM_Write(255, 0);
     EEPROM_Write(254, 0);
     EEPROM_Write(253, 1);
     EEPROM_Write(252, 0);
     EEPROM_Write(251, 0);
     lcd_ind();
     Loss_mode = 0;
     p_Tx = 0;
     n_Tx = 1;
     SWR = 0;
     PWR = 0;
     SWR_fixed_old = 0;
     if (type == 4 | type == 5) { // 128*64 OLED
         led_wr_str(2, 16, "RESET   ", 8);
         asm("CLRWDT");
         delay_ms(600);
         led_wr_str(2, 16, "SWR=0.00", 8);
         asm("CLRWDT");
     } else if (type != 0) {// 1602 LCD & 128*32 OLED
         led_wr_str(1, 0, "RESET   ", 8);
         asm("CLRWDT");
         delay_ms(600);
         led_wr_str(1, 0, "SWR=0.00", 8);
         asm("CLRWDT");
     } else {
         LATBbits.LATB6 = 1;
         LATBbits.LATB7 = 1;
     }
     SWR_old = 10000;
     Power_old = 10000;
     lcd_pwr();
     return;
 }
test_init()
void test_init (void)
tune()
void tune (void)
Definition at line 467 of file main_main.h.
References atu_reset(), cap, cap_mem, coarse_tune(), get_swr(), ind, ind_mem, max_swr, rready, set_cap(), set_ind(), set_sw(), sharp_cap(), sharp_ind(), SW, and SWR.
              {
    int swr_mem, ind_mem, cap_mem;
    asm CLRWDT;
    rready = 0;
    SWR - get_swr();
    if(SWR<110) return;
    atu_reset();
    Delay_ms(10);
    SWR = get_swr();
    if(max_swr>110 & SWR>max_swr) return;
    //
    swr_mem = SWR;
    coarse_tune();
    SWR = get_swr();
    if(SWR<120) return;
    sharp_ind();
    SWR = get_swr();
    if(SWR<120) return;
    sharp_cap();
    SWR = get_swr();
    if(SWR<120) return;
    if(SWR<200 & SWR<swr_mem & (swr_mem-SWR)>100) return;
    swr_mem = SWR;
    ind_mem = ind;
    cap_mem = cap;
    //
    if(SW==1) SW = 0; else SW = 1;
    atu_reset();
    set_sw(SW);
    Delay_ms(10);
    SWR = get_swr();
    //
    coarse_tune();
    SWR = get_swr();
    if(SWR<120) return;
    sharp_ind();
    SWR = get_swr();
    if(SWR<120) return;
    sharp_cap();
    SWR = get_swr();
    if(SWR<120) return;
    //
    if(SWR>swr_mem) {
       if(SW==1) SW = 0; else SW = 1;
       set_sw(SW);
       ind = ind_mem;
       cap = cap_mem;
       set_ind(ind);
       set_cap(cap);
    }
    //
    asm CLRWDT;
    return;
 }
Variable Documentation
C_linear
char C_linear = 0 static
Definition at line 6 of file main_main.h.
C_q
char C_q = 7 static
Definition at line 6 of file main_main.h.
Referenced by sharp_cap().
cap
char cap = 0 static
Definition at line 6 of file main_main.h.
Referenced by atu_reset(), coarse_cap(), coarse_tune(), sharp_cap(), and tune().
D_correction
char D_correction = 1 static
Definition at line 6 of file main_main.h.
Referenced by get_pwr().
ind
char ind = 0 static
Definition at line 6 of file main_main.h.
Referenced by atu_reset(), coarse_tune(), sharp_ind(), and tune().
L_linear
char L_linear = 0 static
Definition at line 6 of file main_main.h.
L_q
char L_q = 7 static
Definition at line 6 of file main_main.h.
Referenced by sharp_ind().
max_for_start
int max_for_start static
Definition at line 7 of file main_main.h.
Referenced by get_swr().
max_swr
int max_swr static
Definition at line 7 of file main_main.h.
Referenced by tune().
min_for_start
int min_for_start static
Definition at line 7 of file main_main.h.
Referenced by get_swr().
PWR
int PWR
Definition at line 8 of file main_main.h.
Referenced by get_pwr(), and get_swr().
Rel_Del
int Rel_Del static
Definition at line 7 of file main_main.h.
Referenced by atu_reset(), set_cap(), set_ind(), and set_sw().
rready
char rready = 0
Definition at line 9 of file main_main.h.
Referenced by get_swr(), and tune().
step_cap
char step_cap = 0 static
Definition at line 6 of file main_main.h.
Referenced by coarse_cap(), coarse_tune(), and sharp_cap().
step_ind
char step_ind = 0 static
Definition at line 6 of file main_main.h.
Referenced by coarse_tune(), and sharp_ind().
SW
char SW = 0 static
Definition at line 6 of file main_main.h.
Referenced by set_sw(), and tune().
SWR
int SWR
Definition at line 8 of file main_main.h.
Referenced by coarse_cap(), coarse_tune(), get_pwr(), get_swr(), sharp_cap(), sharp_ind(), and tune().