ATU100_PIC16F1938: mcc_generated_files/mcc.h File Reference
mcc.h File Reference
#include <xc.h>
#include "device_config.h"
#include "pin_manager.h"
#include <stdint.h>
#include <stdbool.h>
#include <conio.h>
#include "interrupt_manager.h"
#include "ext_int.h"
#include "adc.h"
Function Declarations
void SYSTEM_Initialize (void)
void OSCILLATOR_Initialize (void)
void WDT_Initialize (void)
Function Definitions
OSCILLATOR_Initialize()
void OSCILLATOR_Initialize (void)
@Param none @Returns none @Description Initializes the oscillator to the default states configured in the MCC GUI @Example OSCILLATOR_Initialize(void);
Definition at line 60 of file mcc.c.
{
    // SCS INTOSC; SPLLEN disabled; IRCF 16MHz_HF;
    OSCCON = 0x7A;
    // TUN 0;
    OSCTUNE = 0x00;
    // SBOREN disabled;
    BORCON = 0x00;
}
Referenced by SYSTEM_Initialize().
SYSTEM_Initialize()
void SYSTEM_Initialize (void)
@Generated PIC10 / PIC12 / PIC16 / PIC18 MCUs Header File
@Company: Microchip Technology Inc.
@File Name: mcc.h
@Summary: This is the mcc.h file generated using PIC10 / PIC12 / PIC16 / PIC18 MCUs
@Description: This header file provides implementations for driver APIs for all modules selected in the GUI. Generation Information : Product Revision : PIC10 / PIC12 / PIC16 / PIC18 MCUs - 1.81.7 Device : PIC16F1938 Driver Version : 2.00 The generated drivers are tested against the following: Compiler : XC8 2.31 and above or later MPLAB : MPLAB X 5.45 @Param none @Returns none @Description Initializes the device to the default states configured in the MCC GUI @Example SYSTEM_Initialize(void);
@Generated PIC10 / PIC12 / PIC16 / PIC18 MCUs Source File
@Company: Microchip Technology Inc.
@File Name: mcc.c
@Summary: This is the mcc.c file generated using PIC10 / PIC12 / PIC16 / PIC18 MCUs
@Description: This header file provides implementations for driver APIs for all modules selected in the GUI. Generation Information : Product Revision : PIC10 / PIC12 / PIC16 / PIC18 MCUs - 1.81.7 Device : PIC16F1938 Driver Version : 2.00 The generated drivers are tested against the following: Compiler : XC8 2.31 and above or later MPLAB : MPLAB X 5.45
Definition at line 50 of file mcc.c.
{
    PIN_MANAGER_Initialize();
    OSCILLATOR_Initialize();
    WDT_Initialize();
    EXT_INT_Initialize();
    ADC_Initialize();
}
References ADC_Initialize(), EXT_INT_Initialize(), OSCILLATOR_Initialize(), PIN_MANAGER_Initialize(), and WDT_Initialize().
Referenced by main().
WDT_Initialize()
void WDT_Initialize (void)
@Param none @Returns none @Description Initializes the WDT module to the default states configured in the MCC GUI @Example WDT_Initialize(void);
Definition at line 70 of file mcc.c.
{
    // WDTPS 1:32768; SWDTEN OFF;
    WDTCON = 0x14;
}
Referenced by SYSTEM_Initialize().