ATU100_PIC16F1938: include/oled_control.h File Reference
oled_control.h File Reference
OLED/LCD control definitions for ATU-100 EXT PIC16F1938.
#include <xc.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include "extratypes.h"
#include "preprocessor.h"
#include "common.h"
#include "eeprom_map.h"
Definitions and Macros
#define SoftI2C_SCL LATBbits.LATB6
#define SoftI2C_SDA LATBbits.LATB7
#define SoftI2C_DIR_SCL TRISBbits.TRISB6
#define SoftI2C_DIR_SDA TRISBbits.TRISB7
Function Declarations
void set_addressing (char, char)
void led_send (char)
void led_init (void)
void oled_init (void)
void send_command (char)
void led_wr_str (char, char, char *, char)
void oled_wr_str (char, char, char *, char)
void display_on (void)
void display_off (void)
void Soft_I2C_Init (void)
void Soft_I2C_Start (void)
void Soft_I2C_Write (uint8_t d)
void Soft_I2C_Stop (void)
Variable Declarations
static char RS
static char RW
static char E
static char LED
static char lcd_nibble
static char led_addr
static char led_type
static char shift_line
static char oled_shift
Detailed File Description
OLED/LCD control definitions for ATU-100 EXT PIC16F1938.
Version
3.2.1
Author
Gerad Munsch gmuns.nosp@m.ch@k.nosp@m.d9qzo.nosp@m..com
Date
December 2021
Author
David Fainitski
Date
2016
Definition in file oled_control.h.
Definitions and Macros
SoftI2C_DIR_SCL
#define SoftI2C_DIR_SCL TRISBbits.TRISB6
Definition at line 36 of file oled_control.h.
SoftI2C_DIR_SDA
#define SoftI2C_DIR_SDA TRISBbits.TRISB7
Definition at line 37 of file oled_control.h.
SoftI2C_SCL
#define SoftI2C_SCL LATBbits.LATB6
Definition at line 34 of file oled_control.h.
SoftI2C_SDA
#define SoftI2C_SDA LATBbits.LATB7
Definition at line 35 of file oled_control.h.
Function Definitions
display_off()
void display_off (void)
Referenced by main().
display_on()
void display_on (void)
Definition at line 107 of file oled_control.c.
                  {
    if (led_type > 1) {
        send_command(0xAF); // display ON
    } else if (led_type == 1) {
        LED = 1;
        RS = 0;
        led_send(0);
        led_send(0);
    }
}
References LED, led_send(), led_type, RS, and send_command().
Referenced by button_proc(), and lcd_pwr().
led_init()
void led_init (void)
Definition at line 72 of file oled_control.c.
                    {
    shift_line = EEPROM_read(EEPROM_SHIFT_DOWN);
    oled_shift = EEPROM_read(EEPROM_SHIFT_LEFT);
    if (led_type > 1) {
        oled_init();                // OLED
    } else if (led_type == 1) {     // 1602 LCD display init
        LED = 1;
        RS = 0;                     // Command
        led_send(3);
        delay_ms(5);
        led_send(3);
        delay_ms(1);
        led_send(3);
        led_send(2);
        led_send(2);
        led_send(8);                //
        led_send(0);
        led_send(8);                // LCD OFF
        led_send(0);
        led_send(1);                // LCD clear
        delay_ms(5);
        led_send(0);
        led_send(4 + 2);            // I/D, S
        led_send(0);
        led_send(8 + 4 + 0 + 0);    // LCD ON, Cursor, Blink Cursor
    }
}
References EEPROM_SHIFT_DOWN, EEPROM_SHIFT_LEFT, LED, led_send(), led_type, oled_init(), oled_shift, RS, and shift_line.
Referenced by main().
led_send()
void led_send (char nibble)
Definition at line 32 of file oled_control.c.
{
    char sdata;
    sdata = 0;
    RW = 0;
    E = 1;
    sdata = sdata + nibble;
    sdata = (sdata << 4);
    if (LED) {
        sdata = sdata + 8;
    }
    if (E) {
        sdata = sdata + 4;
    }
    if (RW) {
        sdata = sdata + 2;
    }
    if (RS) {
        sdata = sdata + 1;
    }
    Soft_I2C_Start();
    Soft_I2C_Write(led_addr);       // device address
    Soft_I2C_Write(sdata);          //
    Soft_I2C_Stop();
    delay_ms(1);
    sdata = sdata - 4;              // E = 0
    Soft_I2C_Start();
    Soft_I2C_Write(led_addr);       // device address
    Soft_I2C_Write(sdata);          //
    Soft_I2C_Stop();
    delay_ms(1);
}
References E, LED, led_addr, RS, RW, Soft_I2C_Start(), Soft_I2C_Stop(), and Soft_I2C_Write().
Referenced by display_on(), led_init(), led_wr_str(), and vodisplay_offoff().
led_wr_str()
void led_wr_str (char , char , char * , char)
Referenced by btn_push(), button_proc(), button_proc_test(), lcd_ind(), lcd_prep(), lcd_pwr(), lcd_swr(), main(), show_loss(), show_pwr(), show_reset(), and test_init().
oled_init()
void oled_init (void)
Definition at line 128 of file oled_control.c.
                     { // OLED init
    char i;
    char r;
    Soft_I2C_Start();
    Soft_I2C_Write(led_addr);                       // device address
    Soft_I2C_Write(0x00);                           // 0 - continuous mode, command; 64 - Co, data
    Soft_I2C_Write(0xAE);                           // display OFF
    if ((led_type == 2) || (led_type == 3)) {       // 128*32 OLED
        Soft_I2C_Write(0xD5);                       // clock division
        Soft_I2C_Write(0x80);                       // ratio
        Soft_I2C_Write(0xA8);                       // multiplexer
        Soft_I2C_Write(0x3f);                       // ???
        Soft_I2C_Write(0xD3);                       //  offset
        if (led_type == 2) {
            Soft_I2C_Write(0 + shift_line); /* column shift */
        } else {
            Soft_I2C_Write(31 + shift_line); /* column shift */
        }
        Soft_I2C_Write(0x40); // set line, line = 0
        Soft_I2C_Write(0x8D); //  charge pump
        Soft_I2C_Write(0x14); //  0x10 - external, 0x14 - internal
        Soft_I2C_Write(0x81); //  contrast
        Soft_I2C_Write(180); //   0-255
        Soft_I2C_Write(0xD9); //  pre-charge
        Soft_I2C_Write(0x22); //  0x22 - external, 0xF1 - internal
        Soft_I2C_Write(0x20); //  memory addressing mode
        Soft_I2C_Write(0x02); //  page addressing mode
        Soft_I2C_Write(0x21); // set column range
        Soft_I2C_Write(0); // column start
        Soft_I2C_Write(127); // column stop
        Soft_I2C_Write(0x2E); //  stop scrolling
        if (led_type == 2) {
            Soft_I2C_Write(0xA0); // segment re-map, A0 - normal, A1 - remapped
            Soft_I2C_Write(0xC0); // scan direction, C0 - normal, C8 - remapped
        } else {
            Soft_I2C_Write(0xA1); // segment re-map, A0 - normal, A1 - remapped
            Soft_I2C_Write(0xC8); // scan direction, C0 - normal, C8 - remapped
        }
        Soft_I2C_Write(0xDA); //  COM pins configure
        Soft_I2C_Write(0x02); // 12 for x64
        Soft_I2C_Write(0xDB); //  V-COM detect
        Soft_I2C_Write(0x40); //
    } else { // 128*64 OLED
        Soft_I2C_Write(0xD5); // clock division
        Soft_I2C_Write(0x80); // ratio
        Soft_I2C_Write(0xA8); //  multiplexer
        Soft_I2C_Write(63); //
        Soft_I2C_Write(0xD3); //  offset
        Soft_I2C_Write(shift_line); // no offset for x64 !
        Soft_I2C_Write(0x40); // set line, line = 0
        Soft_I2C_Write(0x8D); //  charge pump
        Soft_I2C_Write(0x14); //  0x10 - external, 0x14 - internal
        Soft_I2C_Write(0x81); //  contrast
        Soft_I2C_Write(255); //   0-255
        Soft_I2C_Write(0xD9); //  pre-charge
        Soft_I2C_Write(0xf1); //  0x22 - external, 0xF1 - internal
        Soft_I2C_Write(0x20); //  memory addressing mode
        Soft_I2C_Write(0x02); //  page addressing mode   02
        Soft_I2C_Write(0x21); // set column range
        Soft_I2C_Write(0); // column start
        Soft_I2C_Write(127); // column stop
        Soft_I2C_Write(0x2E); //  stop scrolling
        if (led_type == 4) {
            Soft_I2C_Write(0xA0); // segment re-map, A0 - normal, A1 - remapped
            Soft_I2C_Write(0xC0); // scan direction, C0 - normal, C8 - remapped
        } else {
            Soft_I2C_Write(0xA1); // segment re-map, A0 - normal, A1 - remapped
            Soft_I2C_Write(0xC8); // scan direction, C0 - normal, C8 - remapped
        }
        Soft_I2C_Write(0xDA); //  COM pins configure
        Soft_I2C_Write(0x12); // 12 for x64
        Soft_I2C_Write(0xDB); //  V-COM detect
        Soft_I2C_Write(0x40); //
    }
    Soft_I2C_Write(0xA4); //  display entire ON
    Soft_I2C_Write(0xA6); // 0xA6 - normal, 0xA7 - inverse
    Soft_I2C_Stop();
    /* ---------- Clear OLED ---------- */
    Delay_ms(100);
    Soft_I2C_Start();
    Soft_I2C_Write(led_addr);                                   // device address
    Soft_I2C_Write(64);                                         // 0 - continuous mode, command; 64 - Co, data
    if ((led_type == 2) || (led_type == 3)) {                   // 128*32 OLED
        for (r = 0; r <= 3; r++) {
            set_addressing(r, 0);                               // clear all 4 pages
            for (i = 0; i < 128; i++, Soft_I2C_Write(0));       // clear one page pixels
        }
    } else {                                                    // 128*64 OLED
        for (r = 0; r <= 7; r++) {
            set_addressing(r, 0); // clear all 8 pages
            for (i = 0; i < 128; i++, Soft_I2C_Write(0x00));    // clear one page pixels
        }
    }
    Soft_I2C_Stop();
    send_command(0xAF);                                         // display ON
}
References led_addr, led_type, send_command(), set_addressing(), shift_line, Soft_I2C_Start(), Soft_I2C_Stop(), and Soft_I2C_Write().
Referenced by led_init().
oled_wr_str()
void oled_wr_str (char , char , char * , char)
send_command()
void send_command (char oled_command)
Definition at line 237 of file oled_control.c.
{
    Soft_I2C_Start();
    Soft_I2C_Write(led_addr); // device addres
    Soft_I2C_Write(128); // 128 - command, 192 - data
    Soft_I2C_Write(oled_command);
    Soft_I2C_Stop();
}
References led_addr, Soft_I2C_Start(), Soft_I2C_Stop(), and Soft_I2C_Write().
Referenced by display_on(), oled_init(), and vodisplay_offoff().
set_addressing()
void set_addressing (char pagenum, char c_start)
Definition at line 245 of file oled_control.c.
{
    char a, b, c;
    c = c_start + oled_shift;
    Soft_I2C_Start();
    Soft_I2C_Write(led_addr); // device addres
    Soft_I2C_Write(0); // 0 - continious mode, command; 64 - Co, data
    Soft_I2C_Write(0xB0 + pagenum); // set page number
    if (c <= 15) {
        a = c;
        b = 0;
    } else {
        b = c / 16;
        a = c - b * 16;
    }
    Soft_I2C_Write(a); // set lower nibble of start address
    Soft_I2C_Write(0x10 + b); // set higher nibble of start address
    Soft_I2C_Start();
    Soft_I2C_Write(led_addr); // device addres
    Soft_I2C_Write(64); // 0 - continious mode, command; 64 - Co, data
}
References led_addr, oled_shift, Soft_I2C_Start(), and Soft_I2C_Write().
Referenced by oled_init(), and oled_wr_str().
Soft_I2C_Init()
void Soft_I2C_Init (void)
Definition at line 391 of file oled_control.c.
                     {
    led_addr = EEPROM_read(EEPROM_OLED_ADDR); //  4E,7E for 1602   or 78, 7A for OLED
    led_type = EEPROM_read(EEPROM_DISP_TYPE);
    if (led_type == 0) {
        Soft_I2C_Scl_Direction = 0;
        Soft_I2C_Sda_Direction = 0;
        SoftI2C_SCL = 1;
        SoftI2C_SDA = 1;
    } else {
        SoftI2C_DIR_SCL = 1;
        Soft_I2C_Sda_Direction = 1;
        SoftI2C_SCL = 0;
        SoftI2C_SDA = 0;
    }
}
References EEPROM_DISP_TYPE, EEPROM_OLED_ADDR, led_addr, led_type, SoftI2C_DIR_SCL, SoftI2C_SCL, and SoftI2C_SDA.
Referenced by main().
Soft_I2C_Start()
void Soft_I2C_Start (void)
Definition at line 408 of file oled_control.c.
                      {
    if (led_type != 0) {
        SoftI2C_DIR_SCL = 1;
        Delay_us(5);
        SoftI2C_DIR_SDA = 1;
        Delay_us(5);
        SoftI2C_DIR_SDA = 0;
        Delay_us(5);
        SoftI2C_DIR_SCL = 0;
        Delay_us(5);
    }
}
References led_type, SoftI2C_DIR_SCL, and SoftI2C_DIR_SDA.
Referenced by led_send(), oled_init(), oled_wr_str(), send_command(), and set_addressing().
Soft_I2C_Stop()
void Soft_I2C_Stop (void)
Definition at line 451 of file oled_control.c.
                     {
    if (led_type != 0) {
        SoftI2C_DIR_SDA = 0;
        Delay_us(5);
        SoftI2C_DIR_SCL = 1;
        Delay_us(5);
        SoftI2C_DIR_SDA = 1;
        Delay_us(5);
    }
}
References led_type, SoftI2C_DIR_SCL, and SoftI2C_DIR_SDA.
Referenced by led_send(), oled_init(), oled_wr_str(), and send_command().
Soft_I2C_Write()
void Soft_I2C_Write (uint8_t d)
Definition at line 421 of file oled_control.c.
{
    char i;
    bit_byte_t bb_d;
    bb_d.byte = d;
    if (led_type != 0) {
        for (i = 0; i <= 7; i++) {
            if (bb_d.B7 == 0) {
                SoftI2C_DIR_SDA = 0;
            } else {
                Soft_I2C_Sda_Direction = 1;
            }
            Delay_us(5);
            SoftI2C_DIR_SCL = 1;
            Delay_us(5);
            SoftI2C_DIR_SCL = 0;
            Delay_us(5);
            d <<= 1;
        }
        SoftI2C_DIR_SDA = 1; //ACK
        Delay_us(5);
        SoftI2C_DIR_SCL = 1;
        Delay_us(5);
        SoftI2C_DIR_SCL = 0;
        Delay_us(5);
    }
}
References bit_byte_t::byte, led_type, SoftI2C_DIR_SCL, and SoftI2C_DIR_SDA.
Referenced by led_send(), oled_init(), oled_wr_str(), send_command(), and set_addressing().
Variable Definitions
E
char E static
Definition at line 43 of file oled_control.h.
Referenced by led_send().
lcd_nibble
char lcd_nibble static
Definition at line 45 of file oled_control.h.
LED
char LED static
Definition at line 44 of file oled_control.h.
Referenced by display_on(), led_init(), led_send(), and vodisplay_offoff().
led_addr
char led_addr static
Definition at line 47 of file oled_control.h.
Referenced by led_send(), oled_init(), oled_wr_str(), send_command(), set_addressing(), and Soft_I2C_Init().
led_type
char led_type static
Definition at line 48 of file oled_control.h.
Referenced by display_on(), led_init(), led_wr_str(), oled_init(), oled_wr_str(), Soft_I2C_Init(), Soft_I2C_Start(), Soft_I2C_Stop(), Soft_I2C_Write(), and vodisplay_offoff().
oled_shift
char oled_shift static
Definition at line 51 of file oled_control.h.
Referenced by led_init(), and set_addressing().
RS
char RS static
Definition at line 41 of file oled_control.h.
Referenced by display_on(), led_init(), led_send(), led_wr_str(), and vodisplay_offoff().
RW
char RW static
Definition at line 42 of file oled_control.h.
Referenced by led_send().
shift_line
char shift_line static
Definition at line 49 of file oled_control.h.
Referenced by led_init(), and oled_init().