ATU100_PIC16F1938: mcc_generated_files/pin_manager.c File Reference
pin_manager.c File Reference
#include "pin_manager.h"
Function Declarations
void PIN_MANAGER_Initialize (void)
void PIN_MANAGER_IOC (void)
void IOCBF0_ISR (void)
void IOCBF0_SetInterruptHandler (void(*InterruptHandler)(void))
void IOCBF0_DefaultInterruptHandler (void)
void IOCBF1_ISR (void)
void IOCBF1_SetInterruptHandler (void(*InterruptHandler)(void))
void IOCBF1_DefaultInterruptHandler (void)
void IOCBF2_ISR (void)
void IOCBF2_SetInterruptHandler (void(*InterruptHandler)(void))
void IOCBF2_DefaultInterruptHandler (void)
Variable Declarations
void(* IOCBF0_InterruptHandler)(void)
void(* IOCBF1_InterruptHandler)(void)
void(* IOCBF2_InterruptHandler)(void)
Function Definitions
IOCBF0_DefaultInterruptHandler()
void IOCBF0_DefaultInterruptHandler (void)
Default interrupt handler for IOCBF0
Definition at line 174 of file pin_manager.c.
{
    // add your IOCBF0 interrupt custom code
    // or set custom function using IOCBF0_SetInterruptHandler()
}
Referenced by PIN_MANAGER_Initialize().
IOCBF0_ISR()
void IOCBF0_ISR (void)
IOCBF0 Interrupt Service Routine
Definition at line 152 of file pin_manager.c.
                      {
    // Add custom IOCBF0 code
    // Call the interrupt handler for the callback registered at runtime
    if(IOCBF0_InterruptHandler)
    {
        IOCBF0_InterruptHandler();
    }
    IOCBFbits.IOCBF0 = 0;
}
References IOCBF0_InterruptHandler.
Referenced by PIN_MANAGER_IOC().
IOCBF0_SetInterruptHandler()
void IOCBF0_SetInterruptHandler (void(*)(void) InterruptHandler)
Allows selecting an interrupt handler for IOCBF0 at application runtime
Definition at line 167 of file pin_manager.c.
{
    IOCBF0_InterruptHandler = InterruptHandler;
}
References IOCBF0_InterruptHandler.
Referenced by PIN_MANAGER_Initialize().
IOCBF1_DefaultInterruptHandler()
void IOCBF1_DefaultInterruptHandler (void)
Default interrupt handler for IOCBF1
Definition at line 204 of file pin_manager.c.
{
    // add your IOCBF1 interrupt custom code
    // or set custom function using IOCBF1_SetInterruptHandler()
}
Referenced by PIN_MANAGER_Initialize().
IOCBF1_ISR()
void IOCBF1_ISR (void)
IOCBF1 Interrupt Service Routine
Definition at line 182 of file pin_manager.c.
                      {
    // Add custom IOCBF1 code
    // Call the interrupt handler for the callback registered at runtime
    if(IOCBF1_InterruptHandler)
    {
        IOCBF1_InterruptHandler();
    }
    IOCBFbits.IOCBF1 = 0;
}
References IOCBF1_InterruptHandler.
Referenced by PIN_MANAGER_IOC().
IOCBF1_SetInterruptHandler()
void IOCBF1_SetInterruptHandler (void(*)(void) InterruptHandler)
Allows selecting an interrupt handler for IOCBF1 at application runtime
Definition at line 197 of file pin_manager.c.
{
    IOCBF1_InterruptHandler = InterruptHandler;
}
References IOCBF1_InterruptHandler.
Referenced by PIN_MANAGER_Initialize().
IOCBF2_DefaultInterruptHandler()
void IOCBF2_DefaultInterruptHandler (void)
Default interrupt handler for IOCBF2
Definition at line 234 of file pin_manager.c.
{
    // add your IOCBF2 interrupt custom code
    // or set custom function using IOCBF2_SetInterruptHandler()
}
Referenced by PIN_MANAGER_Initialize().
IOCBF2_ISR()
void IOCBF2_ISR (void)
IOCBF2 Interrupt Service Routine
Definition at line 212 of file pin_manager.c.
                      {
    // Add custom IOCBF2 code
    // Call the interrupt handler for the callback registered at runtime
    if(IOCBF2_InterruptHandler)
    {
        IOCBF2_InterruptHandler();
    }
    IOCBFbits.IOCBF2 = 0;
}
References IOCBF2_InterruptHandler.
Referenced by PIN_MANAGER_IOC().
IOCBF2_SetInterruptHandler()
void IOCBF2_SetInterruptHandler (void(*)(void) InterruptHandler)
Allows selecting an interrupt handler for IOCBF2 at application runtime
Definition at line 227 of file pin_manager.c.
{
    IOCBF2_InterruptHandler = InterruptHandler;
}
References IOCBF2_InterruptHandler.
Referenced by PIN_MANAGER_Initialize().
PIN_MANAGER_Initialize()
void PIN_MANAGER_Initialize (void)
@Param none @Returns none @Description GPIO and peripheral I/O initialization @Example PIN_MANAGER_Initialize();
LATx registers
TRISx registers
ANSELx registers
WPUx registers
APFCONx registers
IOCx registers
Definition at line 59 of file pin_manager.c.
{
    LATE = 0x00;
    LATA = 0x40;
    LATB = 0x07;
    LATC = 0x00;
    TRISE = 0x08;
    TRISA = 0x3F;
    TRISB = 0xFF;
    TRISC = 0xFF;
    ANSELB = 0x38;
    ANSELA = 0x3F;
    WPUE = 0x00;
    WPUB = 0x07;
    OPTION_REGbits.nWPUEN = 0;
    APFCON = 0x00;
    //interrupt on change for group IOCBF - flag
    IOCBFbits.IOCBF0 = 0;
    //interrupt on change for group IOCBF - flag
    IOCBFbits.IOCBF1 = 0;
    //interrupt on change for group IOCBF - flag
    IOCBFbits.IOCBF2 = 0;
    //interrupt on change for group IOCBN - negative
    IOCBNbits.IOCBN0 = 1;
    //interrupt on change for group IOCBN - negative
    IOCBNbits.IOCBN1 = 1;
    //interrupt on change for group IOCBN - negative
    IOCBNbits.IOCBN2 = 1;
    //interrupt on change for group IOCBP - positive
    IOCBPbits.IOCBP0 = 0;
    //interrupt on change for group IOCBP - positive
    IOCBPbits.IOCBP1 = 0;
    //interrupt on change for group IOCBP - positive
    IOCBPbits.IOCBP2 = 0;
    // register default IOC callback functions at runtime; use these methods to register a custom function
    IOCBF0_SetInterruptHandler(IOCBF0_DefaultInterruptHandler);
    IOCBF1_SetInterruptHandler(IOCBF1_DefaultInterruptHandler);
    IOCBF2_SetInterruptHandler(IOCBF2_DefaultInterruptHandler);
    // Enable IOCI interrupt
    INTCONbits.IOCIE = 1;
}
References IOCBF0_DefaultInterruptHandler(), IOCBF0_SetInterruptHandler(), IOCBF1_DefaultInterruptHandler(), IOCBF1_SetInterruptHandler(), IOCBF2_DefaultInterruptHandler(), and IOCBF2_SetInterruptHandler().
Referenced by SYSTEM_Initialize().
PIN_MANAGER_IOC()
void PIN_MANAGER_IOC (void)
@Param none @Returns none @Description Interrupt on Change Handling routine @Example PIN_MANAGER_IOC();
Definition at line 130 of file pin_manager.c.
{
    // interrupt on change for pin IOCBF0
    if(IOCBFbits.IOCBF0 == 1)
    {
        IOCBF0_ISR();
    }
    // interrupt on change for pin IOCBF1
    if(IOCBFbits.IOCBF1 == 1)
    {
        IOCBF1_ISR();
    }
    // interrupt on change for pin IOCBF2
    if(IOCBFbits.IOCBF2 == 1)
    {
        IOCBF2_ISR();
    }
}
References IOCBF0_ISR(), IOCBF1_ISR(), and IOCBF2_ISR().
Referenced by __interrupt().
Variable Definitions
IOCBF0_InterruptHandler
void(* IOCBF0_InterruptHandler) (void) (void)
Generated Pin Manager File
Company: Microchip Technology Inc.
File Name: pin_manager.c
Summary: This is the Pin Manager file generated using PIC10 / PIC12 / PIC16 / PIC18 MCUs
Description: This header file provides implementations for pin APIs for all pins selected in the GUI. Generation Information : Product Revision : PIC10 / PIC12 / PIC16 / PIC18 MCUs - 1.81.7 Device : PIC16F1938 Driver Version : 2.11 The generated drivers are tested against the following: Compiler : XC8 2.31 and above MPLAB : MPLAB X 5.45
Copyright (c) 2013 - 2015 released Microchip Technology Inc. All rights reserved.
Definition at line 54 of file pin_manager.c.
Referenced by IOCBF0_ISR(), and IOCBF0_SetInterruptHandler().
IOCBF1_InterruptHandler
void(* IOCBF1_InterruptHandler) (void) (void)
@Summary Dynamic Interrupt Handler for IOCBF1 pin
@Description This is a dynamic interrupt handler to be used together with the IOCBF1_SetInterruptHandler() method. This handler is called every time the IOCBF1 ISR is executed and allows any function to be registered at runtime.
@Preconditions Pin Manager intializer called
@Returns None.
@Param None.
@Example PIN_MANAGER_Initialize(); IOCBF1_SetInterruptHandler(IOCBF1_InterruptHandler);
Definition at line 55 of file pin_manager.c.
Referenced by IOCBF1_ISR(), and IOCBF1_SetInterruptHandler().
IOCBF2_InterruptHandler
void(* IOCBF2_InterruptHandler) (void) (void)
@Summary Dynamic Interrupt Handler for IOCBF2 pin
@Description This is a dynamic interrupt handler to be used together with the IOCBF2_SetInterruptHandler() method. This handler is called every time the IOCBF2 ISR is executed and allows any function to be registered at runtime.
@Preconditions Pin Manager intializer called
@Returns None.
@Param None.
@Example PIN_MANAGER_Initialize(); IOCBF2_SetInterruptHandler(IOCBF2_InterruptHandler);
Definition at line 56 of file pin_manager.c.
Referenced by IOCBF2_ISR(), and IOCBF2_SetInterruptHandler().