ATU100_PIC16F1938: mcc_generated_files/pin_manager.h File Reference
pin_manager.h File Reference
#include <xc.h>
Definitions and Macros
#define INPUT 1
#define OUTPUT 0
#define HIGH 1
#define LOW 0
#define ANALOG 1
#define DIGITAL 0
#define PULL_UP_ENABLED 1
#define PULL_UP_DISABLED 0
#define swr_bridge_rev_TRIS TRISAbits.TRISA0
#define swr_bridge_rev_LAT LATAbits.LATA0
#define swr_bridge_rev_PORT PORTAbits.RA0
#define swr_bridge_rev_ANS ANSELAbits.ANSA0
#define swr_bridge_rev_SetHigh() do { LATAbits.LATA0 = 1; } while(0)
#define swr_bridge_rev_SetLow() do { LATAbits.LATA0 = 0; } while(0)
#define swr_bridge_rev_Toggle() do { LATAbits.LATA0 = ~LATAbits.LATA0; } while(0)
#define swr_bridge_rev_GetValue() PORTAbits.RA0
#define swr_bridge_rev_SetDigitalInput() do { TRISAbits.TRISA0 = 1; } while(0)
#define swr_bridge_rev_SetDigitalOutput() do { TRISAbits.TRISA0 = 0; } while(0)
#define swr_bridge_rev_SetAnalogMode() do { ANSELAbits.ANSA0 = 1; } while(0)
#define swr_bridge_rev_SetDigitalMode() do { ANSELAbits.ANSA0 = 0; } while(0)
#define swr_bridge_fwd_TRIS TRISAbits.TRISA1
#define swr_bridge_fwd_LAT LATAbits.LATA1
#define swr_bridge_fwd_PORT PORTAbits.RA1
#define swr_bridge_fwd_ANS ANSELAbits.ANSA1
#define swr_bridge_fwd_SetHigh() do { LATAbits.LATA1 = 1; } while(0)
#define swr_bridge_fwd_SetLow() do { LATAbits.LATA1 = 0; } while(0)
#define swr_bridge_fwd_Toggle() do { LATAbits.LATA1 = ~LATAbits.LATA1; } while(0)
#define swr_bridge_fwd_GetValue() PORTAbits.RA1
#define swr_bridge_fwd_SetDigitalInput() do { TRISAbits.TRISA1 = 1; } while(0)
#define swr_bridge_fwd_SetDigitalOutput() do { TRISAbits.TRISA1 = 0; } while(0)
#define swr_bridge_fwd_SetAnalogMode() do { ANSELAbits.ANSA1 = 1; } while(0)
#define swr_bridge_fwd_SetDigitalMode() do { ANSELAbits.ANSA1 = 0; } while(0)
#define tx_request_n_TRIS TRISAbits.TRISA6
#define tx_request_n_LAT LATAbits.LATA6
#define tx_request_n_PORT PORTAbits.RA6
#define tx_request_n_SetHigh() do { LATAbits.LATA6 = 1; } while(0)
#define tx_request_n_SetLow() do { LATAbits.LATA6 = 0; } while(0)
#define tx_request_n_Toggle() do { LATAbits.LATA6 = ~LATAbits.LATA6; } while(0)
#define tx_request_n_GetValue() PORTAbits.RA6
#define tx_request_n_SetDigitalInput() do { TRISAbits.TRISA6 = 1; } while(0)
#define tx_request_n_SetDigitalOutput() do { TRISAbits.TRISA6 = 0; } while(0)
#define tx_request_p_TRIS TRISAbits.TRISA7
#define tx_request_p_LAT LATAbits.LATA7
#define tx_request_p_PORT PORTAbits.RA7
#define tx_request_p_SetHigh() do { LATAbits.LATA7 = 1; } while(0)
#define tx_request_p_SetLow() do { LATAbits.LATA7 = 0; } while(0)
#define tx_request_p_Toggle() do { LATAbits.LATA7 = ~LATAbits.LATA7; } while(0)
#define tx_request_p_GetValue() PORTAbits.RA7
#define tx_request_p_SetDigitalInput() do { TRISAbits.TRISA7 = 1; } while(0)
#define tx_request_p_SetDigitalOutput() do { TRISAbits.TRISA7 = 0; } while(0)
#define button_tune_TRIS TRISBbits.TRISB0
#define button_tune_LAT LATBbits.LATB0
#define button_tune_PORT PORTBbits.RB0
#define button_tune_WPU WPUBbits.WPUB0
#define button_tune_ANS ANSELBbits.ANSB0
#define button_tune_SetHigh() do { LATBbits.LATB0 = 1; } while(0)
#define button_tune_SetLow() do { LATBbits.LATB0 = 0; } while(0)
#define button_tune_Toggle() do { LATBbits.LATB0 = ~LATBbits.LATB0; } while(0)
#define button_tune_GetValue() PORTBbits.RB0
#define button_tune_SetDigitalInput() do { TRISBbits.TRISB0 = 1; } while(0)
#define button_tune_SetDigitalOutput() do { TRISBbits.TRISB0 = 0; } while(0)
#define button_tune_SetPullup() do { WPUBbits.WPUB0 = 1; } while(0)
#define button_tune_ResetPullup() do { WPUBbits.WPUB0 = 0; } while(0)
#define button_tune_SetAnalogMode() do { ANSELBbits.ANSB0 = 1; } while(0)
#define button_tune_SetDigitalMode() do { ANSELBbits.ANSB0 = 0; } while(0)
#define button_auto_TRIS TRISBbits.TRISB1
#define button_auto_LAT LATBbits.LATB1
#define button_auto_PORT PORTBbits.RB1
#define button_auto_WPU WPUBbits.WPUB1
#define button_auto_ANS ANSELBbits.ANSB1
#define button_auto_SetHigh() do { LATBbits.LATB1 = 1; } while(0)
#define button_auto_SetLow() do { LATBbits.LATB1 = 0; } while(0)
#define button_auto_Toggle() do { LATBbits.LATB1 = ~LATBbits.LATB1; } while(0)
#define button_auto_GetValue() PORTBbits.RB1
#define button_auto_SetDigitalInput() do { TRISBbits.TRISB1 = 1; } while(0)
#define button_auto_SetDigitalOutput() do { TRISBbits.TRISB1 = 0; } while(0)
#define button_auto_SetPullup() do { WPUBbits.WPUB1 = 1; } while(0)
#define button_auto_ResetPullup() do { WPUBbits.WPUB1 = 0; } while(0)
#define button_auto_SetAnalogMode() do { ANSELBbits.ANSB1 = 1; } while(0)
#define button_auto_SetDigitalMode() do { ANSELBbits.ANSB1 = 0; } while(0)
#define button_bypass_TRIS TRISBbits.TRISB2
#define button_bypass_LAT LATBbits.LATB2
#define button_bypass_PORT PORTBbits.RB2
#define button_bypass_WPU WPUBbits.WPUB2
#define button_bypass_ANS ANSELBbits.ANSB2
#define button_bypass_SetHigh() do { LATBbits.LATB2 = 1; } while(0)
#define button_bypass_SetLow() do { LATBbits.LATB2 = 0; } while(0)
#define button_bypass_Toggle() do { LATBbits.LATB2 = ~LATBbits.LATB2; } while(0)
#define button_bypass_GetValue() PORTBbits.RB2
#define button_bypass_SetDigitalInput() do { TRISBbits.TRISB2 = 1; } while(0)
#define button_bypass_SetDigitalOutput() do { TRISBbits.TRISB2 = 0; } while(0)
#define button_bypass_SetPullup() do { WPUBbits.WPUB2 = 1; } while(0)
#define button_bypass_ResetPullup() do { WPUBbits.WPUB2 = 0; } while(0)
#define button_bypass_SetAnalogMode() do { ANSELBbits.ANSB2 = 1; } while(0)
#define button_bypass_SetDigitalMode() do { ANSELBbits.ANSB2 = 0; } while(0)
Function Declarations
void PIN_MANAGER_Initialize (void)
void PIN_MANAGER_IOC (void)
void IOCBF0_ISR (void)
void IOCBF0_SetInterruptHandler (void(*InterruptHandler)(void))
void IOCBF0_DefaultInterruptHandler (void)
void IOCBF1_ISR (void)
void IOCBF1_SetInterruptHandler (void(*InterruptHandler)(void))
void IOCBF1_DefaultInterruptHandler (void)
void IOCBF2_ISR (void)
void IOCBF2_SetInterruptHandler (void(*InterruptHandler)(void))
void IOCBF2_DefaultInterruptHandler (void)
Variable Declarations
void(* IOCBF0_InterruptHandler)(void)
void(* IOCBF1_InterruptHandler)(void)
void(* IOCBF2_InterruptHandler)(void)
Definitions and Macros
ANALOG
#define ANALOG 1
Definition at line 62 of file pin_manager.h.
button_auto_ANS
#define button_auto_ANS ANSELBbits.ANSB1
Definition at line 140 of file pin_manager.h.
button_auto_GetValue
#define button_auto_GetValue () PORTBbits.RB1
Definition at line 144 of file pin_manager.h.
button_auto_LAT
#define button_auto_LAT LATBbits.LATB1
Definition at line 137 of file pin_manager.h.
button_auto_PORT
#define button_auto_PORT PORTBbits.RB1
Definition at line 138 of file pin_manager.h.
button_auto_ResetPullup
#define button_auto_ResetPullup () do { WPUBbits.WPUB1 = 0; } while(0)
Definition at line 148 of file pin_manager.h.
button_auto_SetAnalogMode
#define button_auto_SetAnalogMode () do { ANSELBbits.ANSB1 = 1; } while(0)
Definition at line 149 of file pin_manager.h.
button_auto_SetDigitalInput
#define button_auto_SetDigitalInput () do { TRISBbits.TRISB1 = 1; } while(0)
Definition at line 145 of file pin_manager.h.
button_auto_SetDigitalMode
#define button_auto_SetDigitalMode () do { ANSELBbits.ANSB1 = 0; } while(0)
Definition at line 150 of file pin_manager.h.
button_auto_SetDigitalOutput
#define button_auto_SetDigitalOutput () do { TRISBbits.TRISB1 = 0; } while(0)
Definition at line 146 of file pin_manager.h.
button_auto_SetHigh
#define button_auto_SetHigh () do { LATBbits.LATB1 = 1; } while(0)
Definition at line 141 of file pin_manager.h.
button_auto_SetLow
#define button_auto_SetLow () do { LATBbits.LATB1 = 0; } while(0)
Definition at line 142 of file pin_manager.h.
button_auto_SetPullup
#define button_auto_SetPullup () do { WPUBbits.WPUB1 = 1; } while(0)
Definition at line 147 of file pin_manager.h.
button_auto_Toggle
#define button_auto_Toggle () do { LATBbits.LATB1 = ~LATBbits.LATB1; } while(0)
Definition at line 143 of file pin_manager.h.
button_auto_TRIS
#define button_auto_TRIS TRISBbits.TRISB1
Definition at line 136 of file pin_manager.h.
button_auto_WPU
#define button_auto_WPU WPUBbits.WPUB1
Definition at line 139 of file pin_manager.h.
button_bypass_ANS
#define button_bypass_ANS ANSELBbits.ANSB2
Definition at line 157 of file pin_manager.h.
button_bypass_GetValue
#define button_bypass_GetValue () PORTBbits.RB2
Definition at line 161 of file pin_manager.h.
button_bypass_LAT
#define button_bypass_LAT LATBbits.LATB2
Definition at line 154 of file pin_manager.h.
button_bypass_PORT
#define button_bypass_PORT PORTBbits.RB2
Definition at line 155 of file pin_manager.h.
button_bypass_ResetPullup
#define button_bypass_ResetPullup () do { WPUBbits.WPUB2 = 0; } while(0)
Definition at line 165 of file pin_manager.h.
button_bypass_SetAnalogMode
#define button_bypass_SetAnalogMode () do { ANSELBbits.ANSB2 = 1; } while(0)
Definition at line 166 of file pin_manager.h.
button_bypass_SetDigitalInput
#define button_bypass_SetDigitalInput () do { TRISBbits.TRISB2 = 1; } while(0)
Definition at line 162 of file pin_manager.h.
button_bypass_SetDigitalMode
#define button_bypass_SetDigitalMode () do { ANSELBbits.ANSB2 = 0; } while(0)
Definition at line 167 of file pin_manager.h.
button_bypass_SetDigitalOutput
#define button_bypass_SetDigitalOutput () do { TRISBbits.TRISB2 = 0; } while(0)
Definition at line 163 of file pin_manager.h.
button_bypass_SetHigh
#define button_bypass_SetHigh () do { LATBbits.LATB2 = 1; } while(0)
Definition at line 158 of file pin_manager.h.
button_bypass_SetLow
#define button_bypass_SetLow () do { LATBbits.LATB2 = 0; } while(0)
Definition at line 159 of file pin_manager.h.
button_bypass_SetPullup
#define button_bypass_SetPullup () do { WPUBbits.WPUB2 = 1; } while(0)
Definition at line 164 of file pin_manager.h.
button_bypass_Toggle
#define button_bypass_Toggle () do { LATBbits.LATB2 = ~LATBbits.LATB2; } while(0)
Definition at line 160 of file pin_manager.h.
button_bypass_TRIS
#define button_bypass_TRIS TRISBbits.TRISB2
Definition at line 153 of file pin_manager.h.
button_bypass_WPU
#define button_bypass_WPU WPUBbits.WPUB2
Definition at line 156 of file pin_manager.h.
button_tune_ANS
#define button_tune_ANS ANSELBbits.ANSB0
Definition at line 123 of file pin_manager.h.
button_tune_GetValue
#define button_tune_GetValue () PORTBbits.RB0
Definition at line 127 of file pin_manager.h.
button_tune_LAT
#define button_tune_LAT LATBbits.LATB0
Definition at line 120 of file pin_manager.h.
button_tune_PORT
#define button_tune_PORT PORTBbits.RB0
Definition at line 121 of file pin_manager.h.
button_tune_ResetPullup
#define button_tune_ResetPullup () do { WPUBbits.WPUB0 = 0; } while(0)
Definition at line 131 of file pin_manager.h.
button_tune_SetAnalogMode
#define button_tune_SetAnalogMode () do { ANSELBbits.ANSB0 = 1; } while(0)
Definition at line 132 of file pin_manager.h.
button_tune_SetDigitalInput
#define button_tune_SetDigitalInput () do { TRISBbits.TRISB0 = 1; } while(0)
Definition at line 128 of file pin_manager.h.
button_tune_SetDigitalMode
#define button_tune_SetDigitalMode () do { ANSELBbits.ANSB0 = 0; } while(0)
Definition at line 133 of file pin_manager.h.
button_tune_SetDigitalOutput
#define button_tune_SetDigitalOutput () do { TRISBbits.TRISB0 = 0; } while(0)
Definition at line 129 of file pin_manager.h.
button_tune_SetHigh
#define button_tune_SetHigh () do { LATBbits.LATB0 = 1; } while(0)
Definition at line 124 of file pin_manager.h.
button_tune_SetLow
#define button_tune_SetLow () do { LATBbits.LATB0 = 0; } while(0)
Definition at line 125 of file pin_manager.h.
button_tune_SetPullup
#define button_tune_SetPullup () do { WPUBbits.WPUB0 = 1; } while(0)
Definition at line 130 of file pin_manager.h.
button_tune_Toggle
#define button_tune_Toggle () do { LATBbits.LATB0 = ~LATBbits.LATB0; } while(0)
Definition at line 126 of file pin_manager.h.
button_tune_TRIS
#define button_tune_TRIS TRISBbits.TRISB0
Definition at line 119 of file pin_manager.h.
button_tune_WPU
#define button_tune_WPU WPUBbits.WPUB0
Definition at line 122 of file pin_manager.h.
DIGITAL
#define DIGITAL 0
Definition at line 63 of file pin_manager.h.
HIGH
#define HIGH 1
Definition at line 59 of file pin_manager.h.
INPUT
#define INPUT 1
@Generated Pin Manager Header File
@Company: Microchip Technology Inc.
@File Name: pin_manager.h
@Summary: This is the Pin Manager file generated using PIC10 / PIC12 / PIC16 / PIC18 MCUs
@Description This header file provides APIs for driver for . Generation Information : Product Revision : PIC10 / PIC12 / PIC16 / PIC18 MCUs - 1.81.7 Device : PIC16F1938 Driver Version : 2.11 The generated drivers are tested against the following: Compiler : XC8 2.31 and above MPLAB : MPLAB X 5.45
Section: Included Files
Definition at line 56 of file pin_manager.h.
LOW
#define LOW 0
Definition at line 60 of file pin_manager.h.
OUTPUT
#define OUTPUT 0
Definition at line 57 of file pin_manager.h.
PULL_UP_DISABLED
#define PULL_UP_DISABLED 0
Definition at line 66 of file pin_manager.h.
PULL_UP_ENABLED
#define PULL_UP_ENABLED 1
Definition at line 65 of file pin_manager.h.
swr_bridge_fwd_ANS
#define swr_bridge_fwd_ANS ANSELAbits.ANSA1
Definition at line 86 of file pin_manager.h.
swr_bridge_fwd_GetValue
#define swr_bridge_fwd_GetValue () PORTAbits.RA1
Definition at line 90 of file pin_manager.h.
swr_bridge_fwd_LAT
#define swr_bridge_fwd_LAT LATAbits.LATA1
Definition at line 84 of file pin_manager.h.
swr_bridge_fwd_PORT
#define swr_bridge_fwd_PORT PORTAbits.RA1
Definition at line 85 of file pin_manager.h.
swr_bridge_fwd_SetAnalogMode
#define swr_bridge_fwd_SetAnalogMode () do { ANSELAbits.ANSA1 = 1; } while(0)
Definition at line 93 of file pin_manager.h.
swr_bridge_fwd_SetDigitalInput
#define swr_bridge_fwd_SetDigitalInput () do { TRISAbits.TRISA1 = 1; } while(0)
Definition at line 91 of file pin_manager.h.
swr_bridge_fwd_SetDigitalMode
#define swr_bridge_fwd_SetDigitalMode () do { ANSELAbits.ANSA1 = 0; } while(0)
Definition at line 94 of file pin_manager.h.
swr_bridge_fwd_SetDigitalOutput
#define swr_bridge_fwd_SetDigitalOutput () do { TRISAbits.TRISA1 = 0; } while(0)
Definition at line 92 of file pin_manager.h.
swr_bridge_fwd_SetHigh
#define swr_bridge_fwd_SetHigh () do { LATAbits.LATA1 = 1; } while(0)
Definition at line 87 of file pin_manager.h.
swr_bridge_fwd_SetLow
#define swr_bridge_fwd_SetLow () do { LATAbits.LATA1 = 0; } while(0)
Definition at line 88 of file pin_manager.h.
swr_bridge_fwd_Toggle
#define swr_bridge_fwd_Toggle () do { LATAbits.LATA1 = ~LATAbits.LATA1; } while(0)
Definition at line 89 of file pin_manager.h.
swr_bridge_fwd_TRIS
#define swr_bridge_fwd_TRIS TRISAbits.TRISA1
Definition at line 83 of file pin_manager.h.
swr_bridge_rev_ANS
#define swr_bridge_rev_ANS ANSELAbits.ANSA0
Definition at line 72 of file pin_manager.h.
swr_bridge_rev_GetValue
#define swr_bridge_rev_GetValue () PORTAbits.RA0
Definition at line 76 of file pin_manager.h.
swr_bridge_rev_LAT
#define swr_bridge_rev_LAT LATAbits.LATA0
Definition at line 70 of file pin_manager.h.
swr_bridge_rev_PORT
#define swr_bridge_rev_PORT PORTAbits.RA0
Definition at line 71 of file pin_manager.h.
swr_bridge_rev_SetAnalogMode
#define swr_bridge_rev_SetAnalogMode () do { ANSELAbits.ANSA0 = 1; } while(0)
Definition at line 79 of file pin_manager.h.
swr_bridge_rev_SetDigitalInput
#define swr_bridge_rev_SetDigitalInput () do { TRISAbits.TRISA0 = 1; } while(0)
Definition at line 77 of file pin_manager.h.
swr_bridge_rev_SetDigitalMode
#define swr_bridge_rev_SetDigitalMode () do { ANSELAbits.ANSA0 = 0; } while(0)
Definition at line 80 of file pin_manager.h.
swr_bridge_rev_SetDigitalOutput
#define swr_bridge_rev_SetDigitalOutput () do { TRISAbits.TRISA0 = 0; } while(0)
Definition at line 78 of file pin_manager.h.
swr_bridge_rev_SetHigh
#define swr_bridge_rev_SetHigh () do { LATAbits.LATA0 = 1; } while(0)
Definition at line 73 of file pin_manager.h.
swr_bridge_rev_SetLow
#define swr_bridge_rev_SetLow () do { LATAbits.LATA0 = 0; } while(0)
Definition at line 74 of file pin_manager.h.
swr_bridge_rev_Toggle
#define swr_bridge_rev_Toggle () do { LATAbits.LATA0 = ~LATAbits.LATA0; } while(0)
Definition at line 75 of file pin_manager.h.
swr_bridge_rev_TRIS
#define swr_bridge_rev_TRIS TRISAbits.TRISA0
Definition at line 69 of file pin_manager.h.
tx_request_n_GetValue
#define tx_request_n_GetValue () PORTAbits.RA6
Definition at line 103 of file pin_manager.h.
tx_request_n_LAT
#define tx_request_n_LAT LATAbits.LATA6
Definition at line 98 of file pin_manager.h.
tx_request_n_PORT
#define tx_request_n_PORT PORTAbits.RA6
Definition at line 99 of file pin_manager.h.
tx_request_n_SetDigitalInput
#define tx_request_n_SetDigitalInput () do { TRISAbits.TRISA6 = 1; } while(0)
Definition at line 104 of file pin_manager.h.
tx_request_n_SetDigitalOutput
#define tx_request_n_SetDigitalOutput () do { TRISAbits.TRISA6 = 0; } while(0)
Definition at line 105 of file pin_manager.h.
tx_request_n_SetHigh
#define tx_request_n_SetHigh () do { LATAbits.LATA6 = 1; } while(0)
Definition at line 100 of file pin_manager.h.
tx_request_n_SetLow
#define tx_request_n_SetLow () do { LATAbits.LATA6 = 0; } while(0)
Definition at line 101 of file pin_manager.h.
tx_request_n_Toggle
#define tx_request_n_Toggle () do { LATAbits.LATA6 = ~LATAbits.LATA6; } while(0)
Definition at line 102 of file pin_manager.h.
tx_request_n_TRIS
#define tx_request_n_TRIS TRISAbits.TRISA6
Definition at line 97 of file pin_manager.h.
tx_request_p_GetValue
#define tx_request_p_GetValue () PORTAbits.RA7
Definition at line 114 of file pin_manager.h.
tx_request_p_LAT
#define tx_request_p_LAT LATAbits.LATA7
Definition at line 109 of file pin_manager.h.
tx_request_p_PORT
#define tx_request_p_PORT PORTAbits.RA7
Definition at line 110 of file pin_manager.h.
tx_request_p_SetDigitalInput
#define tx_request_p_SetDigitalInput () do { TRISAbits.TRISA7 = 1; } while(0)
Definition at line 115 of file pin_manager.h.
tx_request_p_SetDigitalOutput
#define tx_request_p_SetDigitalOutput () do { TRISAbits.TRISA7 = 0; } while(0)
Definition at line 116 of file pin_manager.h.
tx_request_p_SetHigh
#define tx_request_p_SetHigh () do { LATAbits.LATA7 = 1; } while(0)
Definition at line 111 of file pin_manager.h.
tx_request_p_SetLow
#define tx_request_p_SetLow () do { LATAbits.LATA7 = 0; } while(0)
Definition at line 112 of file pin_manager.h.
tx_request_p_Toggle
#define tx_request_p_Toggle () do { LATAbits.LATA7 = ~LATAbits.LATA7; } while(0)
Definition at line 113 of file pin_manager.h.
tx_request_p_TRIS
#define tx_request_p_TRIS TRISAbits.TRISA7
Definition at line 108 of file pin_manager.h.
Function Definitions
IOCBF0_DefaultInterruptHandler()
void IOCBF0_DefaultInterruptHandler (void)
@Summary Default Interrupt Handler for IOCBF0 pin
@Description This is a predefined interrupt handler to be used together with the IOCBF0_SetInterruptHandler() method. This handler is called every time the IOCBF0 ISR is executed.
@Preconditions Pin Manager intializer called
@Returns None.
@Param None.
@Example PIN_MANAGER_Initialize(); IOCBF0_SetInterruptHandler(IOCBF0_DefaultInterruptHandler);
Default interrupt handler for IOCBF0
Definition at line 174 of file pin_manager.c.
{
    // add your IOCBF0 interrupt custom code
    // or set custom function using IOCBF0_SetInterruptHandler()
}
Referenced by PIN_MANAGER_Initialize().
IOCBF0_ISR()
void IOCBF0_ISR (void)
@Param none @Returns none @Description Interrupt on Change Handler for the IOCBF0 pin functionality @Example IOCBF0_ISR();
IOCBF0 Interrupt Service Routine
Definition at line 152 of file pin_manager.c.
                      {
    // Add custom IOCBF0 code
    // Call the interrupt handler for the callback registered at runtime
    if(IOCBF0_InterruptHandler)
    {
        IOCBF0_InterruptHandler();
    }
    IOCBFbits.IOCBF0 = 0;
}
References IOCBF0_InterruptHandler.
Referenced by PIN_MANAGER_IOC().
IOCBF0_SetInterruptHandler()
void IOCBF0_SetInterruptHandler (void(*)(void) InterruptHandler)
@Summary Interrupt Handler Setter for IOCBF0 pin interrupt-on-change functionality
@Description Allows selecting an interrupt handler for IOCBF0 at application runtime
@Preconditions Pin Manager intializer called
@Returns None.
@Param InterruptHandler function pointer.
@Example PIN_MANAGER_Initialize(); IOCBF0_SetInterruptHandler(MyInterruptHandler);
Allows selecting an interrupt handler for IOCBF0 at application runtime
Definition at line 167 of file pin_manager.c.
{
    IOCBF0_InterruptHandler = InterruptHandler;
}
References IOCBF0_InterruptHandler.
Referenced by PIN_MANAGER_Initialize().
IOCBF1_DefaultInterruptHandler()
void IOCBF1_DefaultInterruptHandler (void)
@Summary Default Interrupt Handler for IOCBF1 pin
@Description This is a predefined interrupt handler to be used together with the IOCBF1_SetInterruptHandler() method. This handler is called every time the IOCBF1 ISR is executed.
@Preconditions Pin Manager intializer called
@Returns None.
@Param None.
@Example PIN_MANAGER_Initialize(); IOCBF1_SetInterruptHandler(IOCBF1_DefaultInterruptHandler);
Default interrupt handler for IOCBF1
Definition at line 204 of file pin_manager.c.
{
    // add your IOCBF1 interrupt custom code
    // or set custom function using IOCBF1_SetInterruptHandler()
}
Referenced by PIN_MANAGER_Initialize().
IOCBF1_ISR()
void IOCBF1_ISR (void)
@Param none @Returns none @Description Interrupt on Change Handler for the IOCBF1 pin functionality @Example IOCBF1_ISR();
IOCBF1 Interrupt Service Routine
Definition at line 182 of file pin_manager.c.
                      {
    // Add custom IOCBF1 code
    // Call the interrupt handler for the callback registered at runtime
    if(IOCBF1_InterruptHandler)
    {
        IOCBF1_InterruptHandler();
    }
    IOCBFbits.IOCBF1 = 0;
}
References IOCBF1_InterruptHandler.
Referenced by PIN_MANAGER_IOC().
IOCBF1_SetInterruptHandler()
void IOCBF1_SetInterruptHandler (void(*)(void) InterruptHandler)
@Summary Interrupt Handler Setter for IOCBF1 pin interrupt-on-change functionality
@Description Allows selecting an interrupt handler for IOCBF1 at application runtime
@Preconditions Pin Manager intializer called
@Returns None.
@Param InterruptHandler function pointer.
@Example PIN_MANAGER_Initialize(); IOCBF1_SetInterruptHandler(MyInterruptHandler);
Allows selecting an interrupt handler for IOCBF1 at application runtime
Definition at line 197 of file pin_manager.c.
{
    IOCBF1_InterruptHandler = InterruptHandler;
}
References IOCBF1_InterruptHandler.
Referenced by PIN_MANAGER_Initialize().
IOCBF2_DefaultInterruptHandler()
void IOCBF2_DefaultInterruptHandler (void)
@Summary Default Interrupt Handler for IOCBF2 pin
@Description This is a predefined interrupt handler to be used together with the IOCBF2_SetInterruptHandler() method. This handler is called every time the IOCBF2 ISR is executed.
@Preconditions Pin Manager intializer called
@Returns None.
@Param None.
@Example PIN_MANAGER_Initialize(); IOCBF2_SetInterruptHandler(IOCBF2_DefaultInterruptHandler);
Default interrupt handler for IOCBF2
Definition at line 234 of file pin_manager.c.
{
    // add your IOCBF2 interrupt custom code
    // or set custom function using IOCBF2_SetInterruptHandler()
}
Referenced by PIN_MANAGER_Initialize().
IOCBF2_ISR()
void IOCBF2_ISR (void)
@Param none @Returns none @Description Interrupt on Change Handler for the IOCBF2 pin functionality @Example IOCBF2_ISR();
IOCBF2 Interrupt Service Routine
Definition at line 212 of file pin_manager.c.
                      {
    // Add custom IOCBF2 code
    // Call the interrupt handler for the callback registered at runtime
    if(IOCBF2_InterruptHandler)
    {
        IOCBF2_InterruptHandler();
    }
    IOCBFbits.IOCBF2 = 0;
}
References IOCBF2_InterruptHandler.
Referenced by PIN_MANAGER_IOC().
IOCBF2_SetInterruptHandler()
void IOCBF2_SetInterruptHandler (void(*)(void) InterruptHandler)
@Summary Interrupt Handler Setter for IOCBF2 pin interrupt-on-change functionality
@Description Allows selecting an interrupt handler for IOCBF2 at application runtime
@Preconditions Pin Manager intializer called
@Returns None.
@Param InterruptHandler function pointer.
@Example PIN_MANAGER_Initialize(); IOCBF2_SetInterruptHandler(MyInterruptHandler);
Allows selecting an interrupt handler for IOCBF2 at application runtime
Definition at line 227 of file pin_manager.c.
{
    IOCBF2_InterruptHandler = InterruptHandler;
}
References IOCBF2_InterruptHandler.
Referenced by PIN_MANAGER_Initialize().
PIN_MANAGER_Initialize()
void PIN_MANAGER_Initialize (void)
@Param none @Returns none @Description GPIO and peripheral I/O initialization @Example PIN_MANAGER_Initialize();
LATx registers
TRISx registers
ANSELx registers
WPUx registers
APFCONx registers
IOCx registers
Definition at line 59 of file pin_manager.c.
{
    LATE = 0x00;
    LATA = 0x40;
    LATB = 0x07;
    LATC = 0x00;
    TRISE = 0x08;
    TRISA = 0x3F;
    TRISB = 0xFF;
    TRISC = 0xFF;
    ANSELB = 0x38;
    ANSELA = 0x3F;
    WPUE = 0x00;
    WPUB = 0x07;
    OPTION_REGbits.nWPUEN = 0;
    APFCON = 0x00;
    //interrupt on change for group IOCBF - flag
    IOCBFbits.IOCBF0 = 0;
    //interrupt on change for group IOCBF - flag
    IOCBFbits.IOCBF1 = 0;
    //interrupt on change for group IOCBF - flag
    IOCBFbits.IOCBF2 = 0;
    //interrupt on change for group IOCBN - negative
    IOCBNbits.IOCBN0 = 1;
    //interrupt on change for group IOCBN - negative
    IOCBNbits.IOCBN1 = 1;
    //interrupt on change for group IOCBN - negative
    IOCBNbits.IOCBN2 = 1;
    //interrupt on change for group IOCBP - positive
    IOCBPbits.IOCBP0 = 0;
    //interrupt on change for group IOCBP - positive
    IOCBPbits.IOCBP1 = 0;
    //interrupt on change for group IOCBP - positive
    IOCBPbits.IOCBP2 = 0;
    // register default IOC callback functions at runtime; use these methods to register a custom function
    IOCBF0_SetInterruptHandler(IOCBF0_DefaultInterruptHandler);
    IOCBF1_SetInterruptHandler(IOCBF1_DefaultInterruptHandler);
    IOCBF2_SetInterruptHandler(IOCBF2_DefaultInterruptHandler);
    // Enable IOCI interrupt
    INTCONbits.IOCIE = 1;
}
References IOCBF0_DefaultInterruptHandler(), IOCBF0_SetInterruptHandler(), IOCBF1_DefaultInterruptHandler(), IOCBF1_SetInterruptHandler(), IOCBF2_DefaultInterruptHandler(), and IOCBF2_SetInterruptHandler().
Referenced by SYSTEM_Initialize().
PIN_MANAGER_IOC()
void PIN_MANAGER_IOC (void)
@Param none @Returns none @Description Interrupt on Change Handling routine @Example PIN_MANAGER_IOC();
Definition at line 130 of file pin_manager.c.
{
    // interrupt on change for pin IOCBF0
    if(IOCBFbits.IOCBF0 == 1)
    {
        IOCBF0_ISR();
    }
    // interrupt on change for pin IOCBF1
    if(IOCBFbits.IOCBF1 == 1)
    {
        IOCBF1_ISR();
    }
    // interrupt on change for pin IOCBF2
    if(IOCBFbits.IOCBF2 == 1)
    {
        IOCBF2_ISR();
    }
}
References IOCBF0_ISR(), IOCBF1_ISR(), and IOCBF2_ISR().
Referenced by __interrupt().
Variable Definitions
IOCBF0_InterruptHandler
void(* IOCBF0_InterruptHandler) (void) (void) extern
@Summary Dynamic Interrupt Handler for IOCBF0 pin
@Description This is a dynamic interrupt handler to be used together with the IOCBF0_SetInterruptHandler() method. This handler is called every time the IOCBF0 ISR is executed and allows any function to be registered at runtime.
@Preconditions Pin Manager intializer called
@Returns None.
@Param None.
@Example PIN_MANAGER_Initialize(); IOCBF0_SetInterruptHandler(IOCBF0_InterruptHandler);
Generated Pin Manager File
Company: Microchip Technology Inc.
File Name: pin_manager.c
Summary: This is the Pin Manager file generated using PIC10 / PIC12 / PIC16 / PIC18 MCUs
Description: This header file provides implementations for pin APIs for all pins selected in the GUI. Generation Information : Product Revision : PIC10 / PIC12 / PIC16 / PIC18 MCUs - 1.81.7 Device : PIC16F1938 Driver Version : 2.11 The generated drivers are tested against the following: Compiler : XC8 2.31 and above MPLAB : MPLAB X 5.45
Copyright (c) 2013 - 2015 released Microchip Technology Inc. All rights reserved.
Definition at line 54 of file pin_manager.c.
Referenced by IOCBF0_ISR(), and IOCBF0_SetInterruptHandler().
IOCBF1_InterruptHandler
void(* IOCBF1_InterruptHandler) (void) (void) extern
@Summary Dynamic Interrupt Handler for IOCBF1 pin
@Description This is a dynamic interrupt handler to be used together with the IOCBF1_SetInterruptHandler() method. This handler is called every time the IOCBF1 ISR is executed and allows any function to be registered at runtime.
@Preconditions Pin Manager intializer called
@Returns None.
@Param None.
@Example PIN_MANAGER_Initialize(); IOCBF1_SetInterruptHandler(IOCBF1_InterruptHandler);
Definition at line 55 of file pin_manager.c.
Referenced by IOCBF1_ISR(), and IOCBF1_SetInterruptHandler().
IOCBF2_InterruptHandler
void(* IOCBF2_InterruptHandler) (void) (void) extern
@Summary Dynamic Interrupt Handler for IOCBF2 pin
@Description This is a dynamic interrupt handler to be used together with the IOCBF2_SetInterruptHandler() method. This handler is called every time the IOCBF2 ISR is executed and allows any function to be registered at runtime.
@Preconditions Pin Manager intializer called
@Returns None.
@Param None.
@Example PIN_MANAGER_Initialize(); IOCBF2_SetInterruptHandler(IOCBF2_InterruptHandler);
Definition at line 56 of file pin_manager.c.
Referenced by IOCBF2_ISR(), and IOCBF2_SetInterruptHandler().